import { z } from 'zod';
import type { Message, SendRequest } from '@murmur/protocol';
import {
  ConnectorError,
  defineConnector,
  fetchWithTimeout,
  parseMarkers,
  readJson,
  renderTemplate,
  textMessage,
  toolCallToMessage,
  type Connector,
  type ConnectorContext,
} from '@murmur/connector-types';

/**
 * Retell chat agents.
 *
 * Verified against docs.retellai.com on 2026-09-22:
 *   POST  /create-chat                 { agent_id, retell_llm_dynamic_variables? } -> { chat_id }
 *   POST  /create-chat-completion      { chat_id, content } -> { messages: [...] }
 *   PATCH /end-chat/{chat_id}          -> 204
 *
 * A completion returns only the messages generated by that turn — "Does not
 * include the original input messages" — so Retell holds the history and the
 * connector's state is just the chat id.
 */

const BASE_URL = 'https://api.retellai.com';

const secretOrString = z.union([z.string().min(1), z.object({ env: z.string().min(1) })]);

export const retellOptionsSchema = z.object({
  apiKey: secretOrString,
  agentId: z.string().min(1),
  /** Pinned version, or `latest` / `latest_published`. */
  agentVersion: z.union([z.string().min(1), z.number().int().min(0)]).optional(),
  /**
   * Values injected into the agent's prompt, templated from the lead and the
   * page context — `{{lead.name}}`, `{{context.pageUrl}}` (§5).
   */
  dynamicVariables: z.record(z.string().min(1).max(64), z.string().max(500)).optional(),
  /** Parse `[[options: A | B]]` markers when the agent has no tools (§6.3). */
  inlineMarkers: z.boolean().default(false),
  baseUrl: z.string().url().default(BASE_URL),
});

export type RetellOptions = z.infer<typeof retellOptionsSchema>;
export type RetellState = { chatId: string };

function apiKey(options: RetellOptions): string {
  if (typeof options.apiKey === 'string') return options.apiKey;
  throw new ConnectorError('The assistant is not configured correctly.', {
    retryable: false,
    detail: `unresolved_secret:${options.apiKey.env}`,
  });
}

function headers(options: RetellOptions): Record<string, string> {
  return { Authorization: `Bearer ${apiKey(options)}`, 'Content-Type': 'application/json' };
}

/** Turn a non-2xx into a visitor-safe error, keeping the detail for logs. */
async function fail(response: Response, operation: string): Promise<never> {
  const body = await response.text().catch(() => '');
  const retryable = response.status >= 500 || response.status === 429;
  throw new ConnectorError(
    retryable
      ? 'The assistant is busy right now. Please try again.'
      : 'The assistant is unavailable right now.',
    {
      retryable,
      ...(response.status === 429 ? { retryAfter: 20 } : {}),
      // Retell's own text never reaches the visitor (§8.3).
      detail: `retell_${operation}_${response.status}:${body.slice(0, 200)}`,
    },
  );
}

/**
 * Map Retell's message union to protocol messages.
 *
 * `messages` is a union of seven shapes discriminated by `role`. Only the
 * agent's own words and its tool calls are of interest: `user` is the echo of
 * what we just sent, `sms` is a different channel, and the transition and
 * tool-result rows are bookkeeping.
 */
export function mapRetellMessages(raw: unknown, inlineMarkers: boolean): Message[] {
  if (!Array.isArray(raw)) return [];
  const out: Message[] = [];

  for (const entry of raw) {
    if (typeof entry !== 'object' || entry === null) continue;
    const row = entry as Record<string, unknown>;

    if (row['role'] === 'agent' || row['role'] === 'injected') {
      const content = typeof row['content'] === 'string' ? row['content'] : '';
      if (!content) continue;

      if (inlineMarkers) {
        const { text, messages } = parseMarkers(content);
        const body = textMessage(text);
        if (body) out.push(body);
        out.push(...messages);
      } else {
        const body = textMessage(content);
        if (body) out.push(body);
      }
      continue;
    }

    if (row['role'] === 'tool_call_invocation' && typeof row['name'] === 'string') {
      // `arguments` is documented as "a stringified JSON object".
      const built = toolCallToMessage(row['name'], row['arguments']);
      if (built) out.push(built);
    }
  }

  return out;
}

/** `{{lead.name}}` and friends, rendered to the strings Retell expects. */
function dynamicVariables(
  options: RetellOptions,
  scope: { lead?: Record<string, string>; context?: unknown },
): Record<string, string> | undefined {
  const template = options.dynamicVariables;
  if (!template) return undefined;
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(template)) {
    const rendered = renderTemplate(value, scope);
    // An unresolved variable is left out rather than sent as an empty string.
    if (rendered) out[key] = rendered;
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

async function completion(
  ctx: ConnectorContext<RetellOptions>,
  chatId: string,
  content: string,
): Promise<Message[]> {
  const response = await fetchWithTimeout(ctx.fetch, `${ctx.options.baseUrl}/create-chat-completion`, {
    method: 'POST',
    headers: headers(ctx.options),
    body: JSON.stringify({ chat_id: chatId, content }),
  });
  if (!response.ok) await fail(response, 'completion');

  const body = await readJson<{ messages?: unknown }>(response);
  return mapRetellMessages(body.messages, ctx.options.inlineMarkers);
}

const retell: Connector<RetellOptions, RetellState> = {
  type: 'retell',
  optionsSchema: retellOptionsSchema,
  capabilities: { poll: false, end: true },

  async start(ctx, input) {
    const response = await fetchWithTimeout(ctx.fetch, `${ctx.options.baseUrl}/create-chat`, {
      method: 'POST',
      headers: headers(ctx.options),
      body: JSON.stringify({
        agent_id: ctx.options.agentId,
        ...(ctx.options.agentVersion === undefined ? {} : { agent_version: ctx.options.agentVersion }),
        ...(() => {
          const vars = dynamicVariables(ctx.options, { lead: input.lead, context: input.context });
          return vars ? { retell_llm_dynamic_variables: vars } : {};
        })(),
        metadata: { murmur_session: ctx.sessionId, murmur_site: ctx.siteId },
      }),
    });
    if (!response.ok) await fail(response, 'create_chat');

    const body = await readJson<{ chat_id?: unknown }>(response);
    const chatId = typeof body.chat_id === 'string' ? body.chat_id : '';
    if (!chatId) {
      throw new ConnectorError('The assistant could not start a conversation.', {
        retryable: true,
        detail: 'retell_no_chat_id',
      });
    }

    ctx.log('retell.started');
    const messages = input.firstMessage ? await completion(ctx, chatId, input.firstMessage) : [];
    return { state: { chatId }, messages };
  },

  async send(ctx, state, input) {
    // §4.3: the connector acts on an action's value, and the label is what
    // the transcript shows — Retell only takes one string, so it gets the
    // value, which is what the agent's prompt is written against.
    const content = contentFor(input);
    return { messages: await completion(ctx, state.chatId, content) };
  },

  async end(ctx, state) {
    // Fire-and-forget; a failure here costs the visitor nothing.
    const response = await fetchWithTimeout(
      ctx.fetch,
      `${ctx.options.baseUrl}/end-chat/${encodeURIComponent(state.chatId)}`,
      { method: 'PATCH', headers: headers(ctx.options) },
    ).catch(() => null);
    ctx.log('retell.ended', { ok: response?.ok ?? false });
  },
};

function contentFor(input: SendRequest): string {
  return input.kind === 'text' ? input.text : input.value;
}

export const retellConnector = defineConnector(retell);
export default retellConnector;
