import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CliError } from '../errors.js';
import type { Compiled } from './compile.js';
import { GENERATED_DIR, type Project } from './project.js';

/**
 * Writes `.murmur/` — a complete, self-contained Worker project that
 * wrangler can deploy as-is. Regenerated on every deploy; never edited by
 * hand, and gitignored.
 *
 *   .murmur/
 *     wrangler.json   bindings, name, assets
 *     worker.mjs      three lines: import the runtime, import the config
 *     config.json     the compiled server config
 *     runtime/        the prebuilt Murmur server, shipped in this package
 *     assets/         the widget bundles and a preview page
 */

/** Where the prebuilt server and widget live: `dist/runtime`, next to cli.js. */
export function runtimeDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [join(here, 'runtime'), join(here, '..', 'runtime'), join(here, '..', '..', 'dist', 'runtime')];
  const found = candidates.find((dir) => existsSync(join(dir, 'server.js')));
  if (!found) {
    throw new CliError('runtime_missing', 'The Murmur runtime is not built.', {
      hint: 'Inside the Murmur repository run `pnpm --filter @knowtific/murmur build`; the published package ships it prebuilt.',
    });
  }
  return found;
}

/**
 * A fingerprint of the runtime's contents — server, widget and dashboard.
 * Part of the Worker hash, so upgrading murmur redeploys existing Workers
 * even when only a bundle changed and the version number did not.
 */
export function runtimeVersion(): string {
  try {
    const root = runtimeDir();
    const hash = createHash('sha256');
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) walk(path);
        else if (entry.name !== 'version.json') hash.update(entry.name).update(readFileSync(path));
      }
    };
    walk(root);
    return hash.digest('hex').slice(0, 16);
  } catch {
    return 'dev';
  }
}

export function writeWorker(
  projectDir: string,
  compiled: Compiled,
  project: Project,
  options: { dev?: boolean; devVars?: Record<string, string> } = {},
): string {
  const runtime = runtimeDir();
  const out = join(projectDir, GENERATED_DIR, options.dev ? 'dev' : 'deploy');
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });

  writeFileSync(join(out, 'wrangler.json'), `${JSON.stringify(compiled.wrangler, null, 2)}\n`);
  writeFileSync(join(out, 'config.json'), `${JSON.stringify(compiled.serverConfig, null, 2)}\n`);
  writeFileSync(
    join(out, 'worker.mjs'),
    [
      '// Generated by murmur. Do not edit: run `murmur deploy` to regenerate.',
      "import { createApp } from './runtime/server.js';",
      "import config from './config.json';",
      '',
      'export default createApp(config);',
      '',
    ].join('\n'),
  );
  cpSync(join(runtime, 'server.js'), join(out, 'runtime', 'server.js'));
  cpSync(join(runtime, 'widget'), join(out, 'assets'), { recursive: true });
  if (project.dashboard.enabled && existsSync(join(runtime, 'dashboard'))) {
    cpSync(join(runtime, 'dashboard'), join(out, 'assets', 'admin'), { recursive: true });
  }
  writeFileSync(join(out, 'assets', 'index.html'), previewPage(project));
  writeFileSync(join(out, 'assets', 'preview.html'), previewPage(project));

  if (options.devVars) {
    writeFileSync(
      join(out, '.dev.vars'),
      Object.entries(options.devVars)
        .map(([key, value]) => `${key}=${JSON.stringify(value)}`)
        .join('\n') + '\n',
      { mode: 0o600 },
    );
  }
  return out;
}

const escape = (value: string) =>
  value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);

/** The page `murmur deploy` links to: the widget, open, on a neutral backdrop. */
export function previewPage(project: Project): string {
  const name = escape(project.name);
  const accent = /^#[0-9a-f]{3,8}$/i.test(String((project.widget as { brand?: { accent?: string } }).brand?.accent ?? ''))
    ? String((project.widget as { brand?: { accent?: string } }).brand?.accent)
    : '#5B5BF7';
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${name} · chat preview</title>
<style>
  :root { color-scheme: light dark; --accent: ${accent}; }
  body { margin: 0; min-height: 100vh; font: 16px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
    background: Canvas; color: CanvasText; }
  /* Left of centre, so the open chat panel on the right never covers it. */
  main { max-width: 34rem; padding: 12vh 1.25rem 8rem clamp(1.25rem, 8vw, 7rem); }
  h1 { font-size: 1.6rem; margin: 0 0 .5rem; letter-spacing: -0.01em; }
  p { opacity: .8; margin: 0 0 1rem; }
  code { display: block; padding: .8rem 1rem; border-radius: .6rem; font-size: .85rem; overflow-x: auto;
    background: color-mix(in srgb, CanvasText 7%, Canvas); white-space: pre; }
  .dot { display: inline-block; width: .6rem; height: .6rem; border-radius: 50%; background: var(--accent); margin-right: .4rem; }
</style>
</head>
<body>
<main>
  <h1><span class="dot"></span>${name}</h1>
  <p>This is a live preview of your chat assistant. Open it with the button in the corner and ask it something a visitor would.</p>
  <p>To add it to your site, paste this before <code style="display:inline;padding:0 .3rem">&lt;/body&gt;</code>:</p>
  <code id="snippet"></code>
</main>
<script>
  var src = location.origin + '/loader.js';
  document.getElementById('snippet').textContent = '<script src="' + src + '" data-site="${escape(project.site)}" async><\\/script>';
</script>
<script src="/loader.js" data-site="${escape(project.site)}" data-open async></script>
</body>
</html>
`;
}
