import type { Context } from 'hono';
import type { KvStore } from '@helppuff/connector-types';
import type { HelpPuffConfig } from '../config/schema.js';
import { HelpPuffError } from './errors.js';
import { hashIp, resilientKv, type Platform } from './platform.js';
import { Timing } from './timing.js';
import type { ApiKeyRow } from '../api/keys.js';

export type Bindings = {
  /** ≥ 32 bytes, generated by `helppuff deploy`. */
  HELPPUFF_SECRET?: string;
  HELPPUFF_KV?: KvStore;
  /** Set to "1" to log structured events to the console (off in production). */
  HELPPUFF_LOG?: string;
  [key: string]: unknown;
};

export type Variables = {
  helppuff: RequestCtx;
  /** The public API's key for this request, once `api/auth.ts` has checked it. */
  apiKey?: ApiKeyRow;
  /** Who made the request, for the audit log: an email, `key:<id>`, or `admin-key`. */
  actor?: string;
};

export type HonoEnv = { Bindings: Bindings; Variables: Variables };

export type RequestCtx = {
  config: HelpPuffConfig;
  platform: Platform;
  secret: string;
  env: Record<string, unknown>;
  origin: string | null;
  /** SHA-256 of the visitor IP with a secret salt — never the raw IP. */
  ipKey: () => Promise<string>;
  /**
   * The site owner testing from the CLI (`helppuff chat`), proven by a header
   * derived from HELPPUFF_SECRET. Exempt from the per-IP limits, which exist to
   * stop one visitor hammering the site — never from the per-session or
   * daily caps, which bound cost.
   */
  isOwner: () => Promise<boolean>;
  /** Where this request's time goes (see `timing.ts`). */
  timing: Timing;
};

export const OWNER_HEADER = 'X-HelpPuff-Owner';

/** The owner header's value: hex SHA-256 of `<HELPPUFF_SECRET>:owner-test`. */
export async function ownerToken(secret: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(`${secret}:owner-test`));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/** Constant-time comparison of two strings (the owner header against its expected value). */
function sameText(a: string, b: string): boolean {
  let diff = a.length ^ b.length;
  for (let i = 0; i < Math.max(a.length, b.length); i++) diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  return diff === 0;
}

/** Cloudflare's own header. Other platforms set their own in an adapter. */
function extractIp(c: Context<HonoEnv>): string | null {
  return c.req.header('CF-Connecting-IP') ?? c.req.header('X-Forwarded-For')?.split(',')[0]?.trim() ?? null;
}

export function buildRequestCtx(c: Context<HonoEnv>, config: HelpPuffConfig): RequestCtx {
  const env = c.env as unknown as Record<string, unknown>;
  const secret = typeof c.env?.HELPPUFF_SECRET === 'string' ? c.env.HELPPUFF_SECRET : '';
  const debug = c.env?.HELPPUFF_LOG === '1';

  const log: Platform['log'] = (event, data) => {
    if (!debug) return;
    // Structured, PII-free. The only console use in the server.
    console.log(JSON.stringify({ event, ...data }));
  };

  const platform: Platform = {
    kv: resilientKv(c.env?.HELPPUFF_KV, log),
    waitUntil: (promise) => {
      const ctx = c.executionCtx as { waitUntil?: (p: Promise<unknown>) => void } | undefined;
      if (ctx?.waitUntil) ctx.waitUntil(promise.catch(() => {}));
      else void promise.catch(() => {});
    },
    ip: extractIp(c),
    now: () => Date.now(),
    log,
  };

  let cachedIpKey: Promise<string> | null = null;
  let cachedOwner: Promise<boolean> | null = null;
  const presented = c.req.header(OWNER_HEADER);

  return {
    config,
    platform,
    secret,
    env,
    origin: c.req.header('Origin') ?? null,
    ipKey: () => {
      cachedIpKey ??= hashIp(platform.ip, secret || 'unsalted');
      return cachedIpKey;
    },
    timing: new Timing(),
    isOwner: () => {
      cachedOwner ??= presented && secret.length >= 32 ? ownerToken(secret).then((t) => sameText(t, presented)) : Promise.resolve(false);
      return cachedOwner;
    },
  };
}

export function requireSecret(ctx: RequestCtx): string {
  if (ctx.secret.length < 32) {
    ctx.platform.log('config.secret_missing');
    throw new HelpPuffError('internal', { detail: 'helppuff_secret_missing' });
  }
  return ctx.secret;
}

/** Every origin across every site — used only to decide CORS reflection. */
export function allConfiguredOrigins(config: HelpPuffConfig): string[] {
  return Object.values(config.sites).flatMap((site) => site.origins);
}
