import type { Context } from 'hono';
import type { KvStore } from '@murmur/connector-types';
import type { MurmurConfig } from '../config/schema.js';
import { MurmurError } from './errors.js';
import { hashIp, resilientKv, type Platform } from './platform.js';

export type Bindings = {
  /** ≥ 32 bytes, generated by `setup.sh`. */
  MURMUR_SECRET?: string;
  MURMUR_KV?: KvStore;
  /** Set to "1" to log structured events to the console (off in production). */
  MURMUR_LOG?: string;
  [key: string]: unknown;
};

export type Variables = {
  mm: RequestCtx;
};

export type HonoEnv = { Bindings: Bindings; Variables: Variables };

export type RequestCtx = {
  config: MurmurConfig;
  platform: Platform;
  secret: string;
  env: Record<string, unknown>;
  origin: string | null;
  /** SHA-256 of the visitor IP with a secret salt — never the raw IP (§7.2). */
  ipKey: () => Promise<string>;
};

/** Cloudflare's own header. Other platforms set their own in an adapter. */
function extractIp(c: Context<HonoEnv>): string | null {
  return c.req.header('CF-Connecting-IP') ?? c.req.header('X-Forwarded-For')?.split(',')[0]?.trim() ?? null;
}

export function buildRequestCtx(c: Context<HonoEnv>, config: MurmurConfig): RequestCtx {
  const env = c.env as unknown as Record<string, unknown>;
  const secret = typeof c.env?.MURMUR_SECRET === 'string' ? c.env.MURMUR_SECRET : '';
  const debug = c.env?.MURMUR_LOG === '1';

  const log: Platform['log'] = (event, data) => {
    if (!debug) return;
    // Structured, PII-free (§7.2). The only console use in the server.
    console.log(JSON.stringify({ event, ...data }));
  };

  const platform: Platform = {
    kv: resilientKv(c.env?.MURMUR_KV, log),
    waitUntil: (promise) => {
      const ctx = c.executionCtx as { waitUntil?: (p: Promise<unknown>) => void } | undefined;
      if (ctx?.waitUntil) ctx.waitUntil(promise.catch(() => {}));
      else void promise.catch(() => {});
    },
    ip: extractIp(c),
    now: () => Date.now(),
    log,
  };

  let cachedIpKey: Promise<string> | null = null;

  return {
    config,
    platform,
    secret,
    env,
    origin: c.req.header('Origin') ?? null,
    ipKey: () => {
      cachedIpKey ??= hashIp(platform.ip, secret || 'unsalted');
      return cachedIpKey;
    },
  };
}

export function requireSecret(ctx: RequestCtx): string {
  if (ctx.secret.length < 32) {
    ctx.platform.log('config.secret_missing');
    throw new MurmurError('internal', { detail: 'murmur_secret_missing' });
  }
  return ctx.secret;
}

/** Every origin across every site — used only to decide CORS reflection. */
export function allConfiguredOrigins(config: MurmurConfig): string[] {
  return Object.values(config.sites).flatMap((site) => site.origins);
}
