import type { Scope } from './scopes.js';

/**
 * Every route of the API, in one place. The same handlers answer at
 * `/admin/api` (the dashboard and the CLI) and `/api/v1` (the public API);
 * this registry is what makes a route public:
 *
 *  - `api/auth.ts` refuses an API key on any route not listed here, and checks
 *    the listed `scope` (fail closed);
 *  - `pnpm sync:docs` turns it into `openapi.json` and the wiki's API
 *    reference (curl, request, response, errors for each);
 *  - a test checks that every route the app serves under `/api/v1` is listed,
 *    and every listed route exists.
 *
 * `scope: 'any'` needs any valid key; `null` routes are the dashboard's own
 * (sign-in, setup) and answer 404 on `/api/v1`.
 */

export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type Param = { name: string; description: string; required?: boolean; example?: string };

export type Endpoint = {
  method: Method;
  /** Relative to the base URL, Hono style: `/leads/:id`. */
  path: string;
  scope: Scope | 'any' | null;
  tag: string;
  summary: string;
  description?: string;
  query?: Param[];
  /** An example request body (JSON), or `raw` for a binary upload. */
  body?: unknown;
  /** The body's fields, for the reference's table. */
  fields?: Param[];
  raw?: { contentType: string; description: string };
  status?: number;
  /** An example response body; `csv` for a file. */
  response?: unknown;
  /** Response keys that may be null though the example shows a value (for the TypeScript type). */
  nullable?: string[];
  csv?: string;
  /** Errors particular to this route, beyond the common ones. */
  errors?: { status: number; code: string; when: string }[];
};

export const TAGS: { name: string; description: string }[] = [
  { name: 'Account', description: 'Who the key is, and the API description itself.' },
  { name: 'Chat', description: 'Talk to the assistant as a visitor, from your own server: start a conversation, send messages (JSON or streamed), close it.' },
  { name: 'Conversations', description: 'Read, summarise and delete conversations, from the widget and the API alike.' },
  { name: 'Live chat', description: 'A person on the team answers instead of the assistant: reply, take, give, close and hand back a live chat, and see who is available.' },
  { name: 'Labels and notes', description: 'Labels a site defines and puts on conversations (the AI can too), and the team\'s private notes on conversations and contacts.' },
  { name: 'Leads', description: 'The people who gave contact details: your CRM\'s contacts, with custom attributes. Keyed by email per site.' },
  { name: 'Jobs', description: 'Requests, quotes, projects or tickets on the site\'s pipeline: create them from your own forms and systems, move them through the stages, read their history.' },
  { name: 'Callbacks', description: 'Visitors who asked to be called back, as tasks.' },
  { name: 'Knowledge', description: 'What the assistant knows: the website it learned, uploaded files, hand-written knowledge and business details.' },
  { name: 'Prompt', description: 'The business-specific instructions, versioned, and the agent file: the prompt, tools and behaviour settings as one file to export and import.' },
  { name: 'Tools', description: 'Your own APIs, called before, during and after a chat (`{{name}}` in the prompt), and extract tools that save what the assistant learns. What they return is kept on the conversation (`data`) and sent to webhooks.' },
  { name: 'Settings', description: 'The assistant, widget, lead form, limits and IP lists, as one object.' },
  { name: 'Webhooks', description: 'Endpoints that receive events as signed JSON.' },
  { name: 'Analytics', description: 'Totals, usage and the running version.' },
  { name: 'Team', description: 'Who can sign in to the dashboard.' },
  { name: 'API keys', description: 'Keys for this API.' },
  { name: 'Audit', description: 'What changed, when, and who (or which key) changed it.' },
];

const T = 1760000000000;
const message = (text: string) => ({ id: 'm_mfx2k1', ts: T, role: 'agent', type: 'text', text });
const conversationId = '1b0f6a52-3c1e-4c55-9f0e-2d1c7a9e5b10';
const leadId = 'lead_5e3f0c8a-1f7b-4f8e-9a51-0e2b7c4d1a90';
const leadRow = {
  id: leadId,
  site_id: 'acme',
  conversation_id: conversationId,
  name: 'Ada Lovelace',
  email: 'ada@example.com',
  phone: '0400 111 222',
  fields: '{"company":"Analytical Engines"}',
  source: 'form',
  status: 'new',
  notes: null,
  created_at: T,
  updated_at: T,
  company: 'Analytical Engines',
  address: null,
  attributes: { plan: 'pro' },
};
const labelRow = { id: 'lbl_3f2a1b0c9d8e', name: 'Urgent', color: '#ef4444', description: 'Needs an answer today', ai: true };
const noteRow = { id: 'note_mfx2k1a9b3c4', conversationId, leadId, author: 'sam@acme.example', authorName: 'Sam', text: 'Called her back, booked for Tuesday.', createdAt: T, updatedAt: T };
const callback = {
  id: 'cb_mfx2k1a9b3c',
  conversationId,
  leadId,
  name: 'Ada Lovelace',
  phone: '0400 111 222',
  email: 'ada@example.com',
  reason: 'A quote for two rooms',
  status: 'open',
  note: null,
  requestedAt: T,
  closedAt: null,
  closedBy: null,
  pageUrl: 'https://acme.example/pricing',
};
const webhook = {
  id: 'wh_3c2b1a',
  url: 'https://hooks.example.com/helppuff',
  description: 'CRM sync',
  events: ['lead.captured', 'callback.requested'],
  enabled: true,
  secret: 'whsec_0f1e2d3c4b5a69788796a5b4c3d2e1f0a9b8c7d6e5f4',
  lastStatus: 'ok',
  lastError: null,
  lastAt: T,
  createdAt: T,
};
const agentFile = {
  helppuff: 'agent',
  version: 1,
  name: 'Acme Plumbing assistant',
  description: 'Exported from acme on 2025-10-09.',
  prompt: 'If they ask about an order, ask for its number, save it with {{order_number}}, then look it up with {{order_status}}.',
  settings: {
    behaviour: { goal: 'callbacks', tone: 'friendly', length: 'short', prices: 'share' },
    leads: { enabled: true, fields: [{ name: 'name', label: 'Name', type: 'text', required: true }] },
  },
  tools: [
    { name: 'order_number', kind: 'extract', description: 'Save the order number once the visitor gives it.', enabled: true, fields: [{ name: 'order_number', description: 'The order number, like A-1042.', required: true }] },
    {
      name: 'order_status',
      kind: 'http',
      description: 'Look up an order by its number: status, items and delivery date.',
      enabled: true,
      method: 'GET',
      url: 'https://api.acme.example/orders/{{args.order_number}}',
      headers: [{ name: 'Authorization', value: '${ORDER_STATUS_AUTHORIZATION}', secret: true }],
      parameters: [{ name: 'order_number', description: 'The order number, like A-1042.', required: true }],
      pick: ['status', 'delivery.date'],
      keys: ['status', 'delivery.date'],
      timeoutMs: 5000,
      before: false,
      after: false,
    },
  ],
  needs: [{ name: 'ORDER_STATUS_AUTHORIZATION', description: 'The whole Authorization header of the order_status tool' }],
};

const tool = {
  id: 'tool_8d7c6b5a',
  name: 'order_status',
  kind: 'http',
  description: 'Look up an order by its number: status, items and delivery date.',
  method: 'GET',
  url: 'https://api.acme.example/orders/{{args.order_number}}',
  headers: [
    { name: 'Accept', value: 'application/json', secret: false, set: true },
    { name: 'Authorization', value: '', secret: true, set: true },
  ],
  body: '',
  parameters: [{ name: 'order_number', description: 'The order number, like A-1042.', required: true }],
  pick: ['status', 'delivery.date'],
  timeoutMs: 5000,
  keys: ['status', 'delivery', 'delivery.date'],
  before: false,
  after: false,
  when: null,
  enabled: true,
  lastStatus: 200,
  lastError: null,
  lastAt: T,
  createdAt: T,
  updatedAt: T,
};
const keyView = {
  id: 'k7m3p9q2r4s8',
  name: 'Website backend',
  prefix: 'hp_live_k7m3p9q2r4s8',
  site: 'acme',
  scopes: ['chat', 'leads:read'],
  allowIps: [],
  ratePerMinute: 120,
  createdBy: 'owner@acme.example',
  createdAt: T,
  expiresAt: null,
  lastUsedAt: null,
  revokedAt: null,
};
const usage = { day: '2025-10-09', neurons: 1240.5, messages: 64, budget: 9000, freeAllocation: 10000, messagesLeft: 400, state: 'ok' };
const settings = {
  live: { enabled: true, waitSeconds: 120, closeAfterMinutes: 60, showAgentName: true, aiWhileWaiting: false },
  botName: 'Sam',
  businessName: 'Acme Plumbing',
  welcomeMessage: 'Hi, I\'m Sam. How can I help?',
  starterQuestions: ['How much is a blocked drain?'],
  accent: '#5B5BF7',
  position: 'bottom-right',
  launcherIcon: 'chat',
  leads: { enabled: true, fields: [{ name: 'name', label: 'Name', type: 'text', required: true }] },
  assistant: { model: '@cf/zai-org/glm-4.7-flash', locale: 'en-AU', timezone: 'Australia/Sydney', rerank: true, reasoning: 'medium' },
  behaviour: { goal: 'callbacks', tone: 'friendly', length: 'short', prices: 'share' },
  crawl: { schedule: 'weekly', include: [], exclude: [], renderJs: 'auto' },
  security: { limits: { messagesPerSitePerDay: 500, messagesPerIpPerMinute: 10 }, signIn: { attemptsPerIp: 10, attemptsPerAccount: 5, windowMinutes: 15, captcha: true }, allowIps: [], blockIps: [], sessionTtlHours: 24 },
  home: {
    title: 'Hi there',
    subtitle: 'Ask anything, or pick a shortcut.',
    shortcuts: [
      { id: 'ask-1', label: 'How much is a blocked drain?', icon: 'chat', action: { id: 'ask-1', kind: 'reply', label: 'How much is a blocked drain?', value: 'How much is a blocked drain?' } },
      { id: 'call', label: 'Call us', description: '02 9000 0000', icon: 'phone', action: { id: 'call', kind: 'tel', label: 'Call us', phone: '02 9000 0000' } },
    ],
    links: { title: 'Useful pages', items: [{ label: 'Prices', url: 'https://acme.example/prices', description: 'Callouts, drains and hot water' }] },
  },
};
const homeLinks = { title: 'Useful pages', items: [{ label: 'Prices', url: 'https://acme.example/prices', description: 'Callouts, drains and hot water' }, { label: 'Book a plumber', url: 'https://acme.example/book' }] };
const stageRow = { id: 'stg_3f2a1b0c9d8e7f6a', name: 'New request', kind: 'open' };
const jobRow = {
  id: 'job_7c2e9a41b5d03f68',
  number: 1042,
  title: 'Blocked kitchen drain for Ada Lovelace',
  details: 'Kitchen sink drains slowly and gurgles.',
  stage: stageRow,
  status: 'open',
  fields: { service: 'Blocked drains', address: 'Balmain', urgency: 'This week' },
  contact: { id: leadId, name: 'Ada Lovelace', email: 'ada@example.com', phone: '0400 111 222' },
  conversationId,
  source: 'api',
  value: 450,
  valueCents: 45000,
  currency: 'AUD',
  dueAt: null,
  assignedTo: 'sam@acme.example',
  assignedName: 'Sam',
  position: 0,
  stale: false,
  stageChangedAt: T,
  closedAt: null,
  lostReason: null,
  createdAt: T,
  updatedAt: T,
};
const pipelineRow = {
  siteId: 'acme',
  template: 'service-quote',
  itemSingular: 'Job',
  itemPlural: 'Jobs',
  chosenBy: 'ai',
  reason: 'A plumbing business with free on-site quotes.',
  assistantJobs: true,
  quote: { enabled: true, label: 'Get a quote', askContact: true },
  editedAt: null,
  stages: [{ id: stageRow.id, name: 'New request', color: '#3b82f6', position: 0, kind: 'open', rotDays: 1 }],
  fields: [{ id: 'fld_1a2b3c4d5e6f7a8b', name: 'service', label: 'Service', type: 'select', required: false, options: ['Blocked drains', 'Hot water'], question: 'Which service do you need?', position: 0, inQuote: true, quotePosition: 0, archived: false }],
  quotePreview: [{ field: 'service', ask: 'Which service do you need?', input: 'choice', choices: ['Blocked drains', 'Hot water'] }],
};
const templateRow = { id: 'service-quote', name: 'Service quote', description: 'Trades and home or business services that quote before the work.', stages: [{ name: 'New request', kind: 'open', color: '#3b82f6', rotDays: 1 }], fields: [{ name: 'service', label: 'Service', type: 'select', options: [], question: 'Which service do you need?', quote: true }] };
const siteQuery: Param = { name: 'site', description: 'The site (a key always uses its own).', example: 'acme' };

export const ENDPOINTS: Endpoint[] = [
  // ------------------------------------------------------------------ account
  {
    method: 'GET',
    path: '/me',
    scope: 'any',
    tag: 'Account',
    summary: 'Who is calling',
    description: 'The key (or account) and the site it works on. A cheap way to check a key.',
    response: {
      admin: { email: 'key:k7m3p9q2r4s8', owner: false, role: 'admin', name: 'Website backend', via: 'key' },
      key: { id: 'k7m3p9q2r4s8', name: 'Website backend', scopes: ['chat', 'leads:read'], site: 'acme', expiresAt: null },
      sites: [{ id: 'acme', name: 'Acme Plumbing', accent: '#5B5BF7', avatar: null, embed: '<script src="https://helppuff.example.workers.dev/loader.js" data-site="acme" async></script>', connector: 'workers-ai', knowledge: true, website: 'https://acme.example', production: { turnstile: true, hostnames: ['acme.example', 'helppuff.example.workers.dev'], dailyCap: 500 }, live: true, prompt: true }],
      summaries: true,
    },
  },
  // --------------------------------------------------------------------- chat
  {
    method: 'POST',
    path: '/conversations',
    scope: 'chat',
    tag: 'Chat',
    summary: 'Start a conversation',
    description:
      'Starts a conversation as a visitor would, with the same assistant, knowledge, limits and recording as the widget. With `message`, the answer has the assistant\'s reply; send `Accept: text/event-stream` to stream it: `delta` events with `{ text }` as it is written, then `done` with this body (or `error` with the error), when the AI backend streams; otherwise the answer is plain JSON. `contact` becomes (or joins, by email) a lead. Counts against the site\'s daily cap.',
    fields: [
      { name: 'message', description: 'The visitor\'s first message (up to 4000 characters). Without one, the answer is the greeting, if any.' },
      { name: 'contact', description: 'What you know about the visitor: `name`, `email`, `phone` and any other fields (up to 20). Becomes, or joins by email, a lead.' },
      { name: 'user', description: 'A signed-in visitor, as your server knows them: `id` (your user id) and any fields (`email`, `plan`, up to 20). Trusted, since the key is the proof: tools and the prompt read it as `{{user.*}}`, and its email and name become the lead\'s. From a browser, use a signed token instead (`HelpPuff.identify({ token })`).' },
      { name: 'context', description: '`pageUrl`, `pageTitle`, `referrer`, `locale`, `timezone`, `utm`: where the visitor is. The assistant may use it.' },
      { name: 'externalId', description: 'Your own id for this conversation or visitor (up to 128 characters), to find it again.' },
      { name: 'metadata', description: 'Up to 20 string values you want back later. Never shown to the assistant.' },
      { name: 'site', description: 'Only with the admin key and several sites; a key uses its own.' },
    ],
    body: {
      message: 'How much is a blocked drain?',
      contact: { name: 'Ada Lovelace', email: 'ada@example.com' },
      context: { pageUrl: 'https://app.example.com/help', locale: 'en-AU' },
      externalId: 'user-123',
      metadata: { plan: 'pro' },
    },
    status: 201,
    nullable: ['externalId', 'metadata'],
    response: {
      id: conversationId,
      messages: [message('A blocked drain is usually $180–$250, including the first hour. Would you like a callback to book it in?')],
      externalId: 'user-123',
      metadata: { plan: 'pro' },
    },
    errors: [
      { status: 429, code: 'quota_exceeded', when: 'The site used its daily cap (`security.limits.messagesPerSitePerDay`).' },
      { status: 502, code: 'connector_error', when: 'The AI backend failed; try again.' },
    ],
  },
  {
    method: 'POST',
    path: '/conversations/:id/messages',
    scope: 'chat',
    tag: 'Chat',
    summary: 'Send a message',
    description:
      'The visitor\'s next message: `{ "text" }`, or `{ "action": { id, value, label? } }` to answer options, a card button or a form (a form\'s answers are a JSON object string in `value`; forms are honoured only when this conversation was shown them). Only conversations started over the API can be continued here. `Accept: text/event-stream` streams the reply.',
    fields: [
      { name: 'text', description: 'What the visitor typed (up to `maxMessageLength`). Or, instead:' },
      { name: 'action', description: '`{ id, value, label? }`: an answer to options, a card button or a form. `id` is the message (or action) id; a form\'s answers are a JSON object string in `value`.' },
    ],
    body: { text: 'Can someone come tomorrow morning?' },
    response: { id: conversationId, messages: [message('Tomorrow morning works. What is the best number to reach you on?')] },
    errors: [
      { status: 400, code: 'bad_request', when: 'Empty or too long (`maxMessageLength`), or a form this conversation was not shown.' },
      { status: 404, code: 'not_found', when: 'No conversation started over the API with this id.' },
      { status: 429, code: 'quota_exceeded', when: 'The conversation reached `messagesPerSession`, or the site its daily cap.' },
    ],
  },
  {
    method: 'POST',
    path: '/conversations/:id/end',
    scope: 'chat',
    tag: 'Chat',
    summary: 'Close a conversation',
    description: 'Ends it for the AI backend and sends `conversation.ended` (once). It stays readable.',
    response: { id: conversationId, ended: true },
  },
  // ------------------------------------------------------------ conversations
  {
    method: 'GET',
    path: '/conversations',
    scope: 'conversations:read',
    tag: 'Conversations',
    summary: 'List conversations',
    description: 'Newest activity first, 30 at a time. Pass `next` from the answer as `before` for the next page.',
    query: [
      { name: 'q', description: 'Search messages, summaries and lead details (up to 48 characters).', example: 'drain' },
      { name: 'filter', description: '`all`, `leads` (with a lead), `unsummarized`, `callbacks` (with an open callback request) or `waiting` (a live chat waiting for the team\'s reply).', example: 'leads' },
      { name: 'status', description: '`all`, `bot` (the assistant has it), `live` (a person has it) or `closed` (closed, or quiet for `live.closeAfterMinutes`).', example: 'live' },
      { name: 'label', description: 'Conversations with this label (its id or name).', example: 'Urgent' },
      { name: 'assigned', description: '`me`, `none`, or a team member\'s email.', example: 'none' },
      { name: 'externalId', description: 'Conversations started over the API with this `externalId`.', example: 'user-123' },
      { name: 'before', description: 'Cursor: the `next` of the previous page.' },
      { name: 'limit', description: '1–100, default 30.', example: '30' },
      siteQuery,
    ],
    response: {
      items: [
        {
          id: conversationId,
          site: 'acme',
          startedAt: T,
          lastAt: T + 120000,
          pageUrl: 'https://acme.example/pricing',
          country: 'AU',
          firstMessage: 'How much is a blocked drain?',
          messageCount: 6,
          summary: 'Ada asked about a blocked drain and booked a callback.',
          intent: 'Pricing question',
          leadName: 'Ada Lovelace',
          leadEmail: 'ada@example.com',
          leadPhone: '0400 111 222',
          leadStatus: 'new',
          callback: 'open',
          status: 'live',
          assignedTo: 'sam@acme.example',
          assignedName: 'Sam',
          waitingSince: T + 120000,
          attributes: { orderId: 'A-1042' },
          labels: [{ id: labelRow.id, name: labelRow.name, color: labelRow.color }],
        },
      ],
      next: null,
    },
    nullable: ['assignedTo', 'assignedName', 'waitingSince'],
  },
  {
    method: 'GET',
    path: '/conversations/:id',
    scope: 'conversations:read',
    tag: 'Conversations',
    summary: 'Get a conversation',
    description: 'The conversation (with its `status`, who has it, custom `attributes`, `data`: what the site\'s tools returned or saved, by tool name, and `user`: the signed-in visitor, verified, or null), its lead, callback requests, labels, the team\'s notes and every message both ways (a person\'s replies carry `author`).',
    response: {
      conversation: {
        id: conversationId,
        site_id: 'acme',
        started_at: T,
        last_at: T + 120000,
        page_url: 'https://acme.example/pricing',
        page_title: 'Pricing',
        referrer: null,
        utm: null,
        locale: 'en-AU',
        country: 'AU',
        first_message: 'How much is a blocked drain?',
        message_count: 2,
        lead_id: leadId,
        summary: null,
        intent: null,
        summarized_at: null,
        completed_at: null,
        ended_at: null,
        channel: 'widget',
        status: 'bot',
        assigned_to: null,
        assigned_name: null,
        handover_at: null,
        waiting_since: null,
        closed_at: null,
        attributes: { orderId: 'A-1042' },
        data: { order_status: { status: 'shipped', delivery: { date: '2026-10-12' } } },
        user: { id: 'u_8812', email: 'ada@example.com', plan: 'pro' },
      },
      lead: leadRow,
      callbacks: [callback],
      labels: [{ id: labelRow.id, name: labelRow.name, color: labelRow.color, addedBy: 'ai', addedAt: T }],
      notes: [{ id: noteRow.id, author: noteRow.author, authorName: noteRow.authorName, text: noteRow.text, createdAt: T, updatedAt: T }],
      messages: [
        { id: `${conversationId}:u1`, role: 'user', type: 'text', text: 'How much is a blocked drain?', payload: null, ts: T, feedback: null, author: null },
        { id: `${conversationId}:m_mfx2k1`, role: 'agent', type: 'text', text: 'Usually $180–$250.', payload: {}, ts: T + 1, feedback: 1, author: null },
      ],
    },
    nullable: ['user'],
  },
  {
    method: 'PATCH',
    path: '/conversations/:id',
    scope: 'conversations:write',
    tag: 'Conversations',
    summary: 'Label a conversation, or set its attributes',
    description:
      'Custom `attributes` are key-value strings for your own data (an order number, a plan): sent keys are set, `null` removes one, others stay; up to 50. Labels come from the site\'s list (`GET /labels`), by id or name: `labels` replaces them, `addLabels` and `removeLabels` change them.',
    fields: [
      { name: 'attributes', description: 'An object of strings; `null` removes a key. Keys: up to 64 letters, digits, spaces, `_ - .`; values up to 1000 characters.' },
      { name: 'labels', description: 'The labels it should have (ids or names), replacing the ones it has.' },
      { name: 'addLabels', description: 'Labels to add.' },
      { name: 'removeLabels', description: 'Labels to remove.' },
    ],
    body: { attributes: { orderId: 'A-1042', coupon: null }, addLabels: ['Urgent'] },
    response: { id: conversationId, labels: [{ id: labelRow.id, name: labelRow.name, color: labelRow.color, addedBy: 'key:k7m3p9q2r4s8', addedAt: T }], attributes: { orderId: 'A-1042' }, data: {}, notes: [] },
    errors: [{ status: 400, code: 'bad_request', when: 'An unknown label, a bad attribute key or value, or more than 50 attributes.' }],
  },
  {
    method: 'POST',
    path: '/conversations/:id/notes',
    scope: 'conversations:write',
    tag: 'Labels and notes',
    summary: 'Add a note to a conversation',
    description: 'A private note for the team: never shown to the visitor or the assistant. It also shows on the contact.',
    fields: [{ name: 'text', description: 'Up to 5000 characters.', required: true }],
    body: { text: 'Called her back, booked for Tuesday.' },
    status: 201,
    response: noteRow,
    nullable: ['leadId', 'authorName'],
  },
  {
    method: 'PATCH',
    path: '/notes/:id',
    scope: 'conversations:write',
    tag: 'Labels and notes',
    summary: 'Edit a note',
    fields: [{ name: 'text', description: 'Up to 5000 characters.', required: true }],
    body: { text: 'Booked for Tuesday 9am.' },
    response: { ...noteRow, text: 'Booked for Tuesday 9am.' },
    nullable: ['conversationId', 'leadId', 'authorName'],
  },
  {
    method: 'DELETE',
    path: '/notes/:id',
    scope: 'conversations:write',
    tag: 'Labels and notes',
    summary: 'Delete a note',
    response: { id: noteRow.id, deleted: true },
  },
  {
    method: 'GET',
    path: '/labels',
    scope: 'conversations:read',
    tag: 'Labels and notes',
    summary: 'List labels',
    description: 'The site\'s labels, with the colours there are. `ai`: the AI may put it on a conversation when it goes quiet, guided by `description`.',
    query: [siteQuery],
    response: { labels: [labelRow], colors: ['#6b7280', '#ef4444', '#3b82f6'] },
  },
  {
    method: 'POST',
    path: '/labels',
    scope: 'settings:write',
    tag: 'Labels and notes',
    summary: 'Create a label',
    fields: [
      { name: 'name', description: 'Up to 40 characters, one per name.', required: true },
      { name: 'color', description: 'A hex colour like `#3b82f6`; one is picked if left out.' },
      { name: 'description', description: 'What it means (up to 200 characters): the AI reads it to decide.' },
      { name: 'ai', description: 'Whether the AI may use it (default true).' },
    ],
    body: { name: 'Urgent', color: '#ef4444', description: 'Needs an answer today' },
    status: 201,
    response: labelRow,
    nullable: ['description'],
    errors: [{ status: 409, code: 'conflict', when: 'A label with this name exists.' }],
  },
  {
    method: 'PATCH',
    path: '/labels/:id',
    scope: 'settings:write',
    tag: 'Labels and notes',
    summary: 'Change a label',
    fields: [
      { name: 'name', description: 'Up to 40 characters.' },
      { name: 'color', description: 'A hex colour.' },
      { name: 'description', description: 'What it means.' },
      { name: 'ai', description: 'Whether the AI may use it.' },
    ],
    body: { ai: false },
    response: { ...labelRow, ai: false },
    nullable: ['description'],
  },
  {
    method: 'DELETE',
    path: '/labels/:id',
    scope: 'settings:write',
    tag: 'Labels and notes',
    summary: 'Delete a label',
    description: 'Removes it from every conversation too.',
    response: { id: labelRow.id, deleted: true },
  },
  // ---------------------------------------------------------------- live chat
  {
    method: 'GET',
    path: '/live/status',
    scope: 'conversations:read',
    tag: 'Live chat',
    summary: 'Live chat now',
    description: 'Whether live chat is on, who on the team can take chats (an open dashboard set to available), whether Telegram is linked, and how many live chats there are: unassigned, waiting for a reply, and waiting for you.',
    query: [siteQuery],
    response: {
      enabled: true,
      hub: true,
      available: 1,
      agents: [{ email: 'sam@acme.example', name: 'Sam', available: true }],
      telegram: { connected: true, linked: true },
      live: 2,
      unassigned: 1,
      waiting: 1,
      mine: 0,
    },
  },
  {
    method: 'POST',
    path: '/conversations/:id/reply',
    scope: 'conversations:write',
    tag: 'Live chat',
    summary: 'Reply in a live chat',
    description: 'A person on the team answers the visitor (shown with their first name, `live.showAgentName`). Any conversation: replying to one the assistant has, or a closed one, takes it over first (it becomes live). Needs live chat on. Sends `message.sent` with `author`.',
    fields: [{ name: 'text', description: 'Up to 4000 characters.', required: true }],
    body: { text: 'Hi Ada, Sam here. Tomorrow at 9 works — shall I book it?' },
    status: 201,
    response: { id: 'h_mfx2k1a9', ts: T, role: 'agent', type: 'text', text: 'Hi Ada, Sam here. Tomorrow at 9 works — shall I book it?', meta: { human: true, agentName: 'Sam' } },
    errors: [{ status: 400, code: 'bad_request', when: 'Live chat is off, or the message is empty.' }],
  },
  {
    method: 'POST',
    path: '/conversations/:id/takeover',
    scope: 'conversations:write',
    tag: 'Live chat',
    summary: 'Take a conversation over',
    description:
      'A signed-in person takes the chat, whatever it is doing: from the assistant, from a colleague, or closed (this reopens it). It becomes live and theirs; the visitor sees who joined, at once if their chat is open. For a key, reply instead (`POST /conversations/:id/reply` takes it over too). Sends `conversation.assigned`.',
    response: { conversationId, status: 'live', assignedTo: 'sam@acme.example', assignedName: 'Sam' },
    nullable: ['assignedName'],
    errors: [{ status: 400, code: 'bad_request', when: 'Live chat is off, or called with an API key (use reply).' }],
  },
  {
    method: 'POST',
    path: '/conversations/:id/assign',
    scope: 'conversations:write',
    tag: 'Live chat',
    summary: 'Take or give a conversation',
    description: '`to`: `"me"` (a signed-in person takes it), a team member\'s email (give it; admins only), or `null` (unassign). The visitor of a live chat sees who joined. Sends `conversation.assigned`.',
    fields: [{ name: 'to', description: '`"me"`, an email on the team, or null.', required: true }],
    body: { to: 'sam@acme.example' },
    response: { conversationId, assignedTo: 'sam@acme.example', assignedName: 'Sam' },
    nullable: ['assignedTo', 'assignedName'],
  },
  {
    method: 'POST',
    path: '/conversations/:id/close',
    scope: 'conversations:write',
    tag: 'Live chat',
    summary: 'Close a conversation',
    description: 'Closes it (conversations also close after `live.closeAfterMinutes` without a message). The visitor of a live chat is told; if they write again, the assistant answers. Sends `conversation.closed`.',
    response: { conversationId, status: 'closed', closedAt: T },
  },
  {
    method: 'POST',
    path: '/conversations/:id/handback',
    scope: 'conversations:write',
    tag: 'Live chat',
    summary: 'Hand back to the assistant',
    description: 'Ends the live part, or reopens a closed conversation for the assistant: it answers the visitor\'s next message. The team can take it over again at any time. Sends `handover.ended`.',
    response: { conversationId, status: 'bot' },
    errors: [{ status: 409, code: 'conflict', when: 'The assistant already has it.' }],
  },
  {
    method: 'GET',
    path: '/live/telegram',
    scope: 'settings:read',
    tag: 'Live chat',
    summary: 'Telegram',
    description: 'Whether a Telegram bot is connected and linked to a chat; until linked, the `linkCode` to send there as `/link <code>`.',
    query: [siteQuery],
    response: { connected: true, linked: true, bot: { name: 'Acme Desk', username: 'acme_desk_bot' }, chat: { title: 'Acme team', topics: true }, linkCode: null, shareContact: true, status: 'ok', lastError: null, updatedAt: T },
    nullable: ['bot', 'chat', 'linkCode', 'status', 'lastError', 'updatedAt'],
  },
  {
    method: 'POST',
    path: '/live/telegram',
    scope: 'settings:write',
    tag: 'Live chat',
    summary: 'Connect Telegram',
    description:
      'Connects the bot made with @BotFather by its token (checked with `getMe`, stored encrypted), and points its webhook here. Then add the bot to your team\'s group (Topics on, the bot an admin with "Manage topics"), or open a private chat with it, and send `/link <linkCode>` there.',
    fields: [{ name: 'token', description: 'The bot token from @BotFather.', required: true }],
    body: { token: '7123456789:AAH3k…' },
    status: 201,
    response: { connected: true, linked: false, bot: { name: 'Acme Desk', username: 'acme_desk_bot' }, chat: null, linkCode: '9f3a1c2e', shareContact: true, status: 'linking', lastError: null, updatedAt: T },
    nullable: ['bot', 'chat', 'linkCode', 'status', 'lastError', 'updatedAt'],
    errors: [{ status: 400, code: 'bad_request', when: 'Telegram refused the token, or the webhook.' }],
  },
  {
    method: 'PATCH',
    path: '/live/telegram',
    scope: 'settings:write',
    tag: 'Live chat',
    summary: 'Change Telegram options',
    fields: [{ name: 'shareContact', description: 'Include visitors\' email and phone in what goes to Telegram.' }],
    body: { shareContact: false },
    response: { connected: true, linked: true, bot: { name: 'Acme Desk', username: 'acme_desk_bot' }, chat: { title: 'Acme team', topics: true }, linkCode: null, shareContact: false, status: 'ok', lastError: null, updatedAt: T },
    nullable: ['bot', 'chat', 'linkCode', 'status', 'lastError', 'updatedAt'],
  },
  {
    method: 'POST',
    path: '/live/telegram/test',
    scope: 'settings:write',
    tag: 'Live chat',
    summary: 'Send a Telegram test',
    response: { ok: true },
    errors: [{ status: 400, code: 'bad_request', when: 'No chat is linked yet.' }],
  },
  {
    method: 'DELETE',
    path: '/live/telegram',
    scope: 'settings:write',
    tag: 'Live chat',
    summary: 'Disconnect Telegram',
    query: [siteQuery],
    response: { connected: false },
  },
  {
    method: 'POST',
    path: '/conversations/:id/summary',
    scope: 'conversations:write',
    tag: 'Conversations',
    summary: 'Summarise a conversation',
    description: 'Writes (or rewrites) its AI summary and labels, and sends `conversation.summarized`. Uses Workers AI (a few neurons). Conversations are also summarised automatically 5 minutes after they go quiet.',
    response: {
      summary: 'Ada asked about a blocked drain and booked a callback for tomorrow morning.',
      intent: 'Blocked drain',
      sentiment: 'positive',
      leadQuality: 'hot',
      outcome: 'callback_requested',
      topics: ['drains', 'pricing'],
      unanswered: [],
      followUp: 'Call Ada tomorrow before 10am.',
      lead: { name: 'Ada Lovelace', phone: '0400 111 222' },
    },
  },
  {
    method: 'DELETE',
    path: '/conversations/:id',
    scope: 'conversations:write',
    tag: 'Conversations',
    summary: 'Delete a conversation',
    description: 'Deletes it with its messages and callback requests. The lead it produced stays (delete it with `DELETE /leads/:id`).',
    response: { id: conversationId, deleted: true },
  },
  // -------------------------------------------------------------------- leads
  {
    method: 'GET',
    path: '/leads',
    scope: 'leads:read',
    tag: 'Leads',
    summary: 'List leads',
    description: 'Most recently updated first, up to 500, with counts by status.',
    query: [
      { name: 'q', description: 'Search name, email, phone, company, notes and attributes.', example: 'ada' },
      { name: 'status', description: '`new`, `contacted`, `qualified`, `won` or `lost`.', example: 'new' },
      siteQuery,
    ],
    response: {
      items: [
        {
          id: leadId,
          site: 'acme',
          conversationId,
          name: 'Ada Lovelace',
          email: 'ada@example.com',
          phone: '0400 111 222',
          company: 'Analytical Engines',
          address: null,
          fields: '{"company":"Analytical Engines"}',
          attributes: { plan: 'pro' },
          source: 'form',
          status: 'new',
          notes: null,
          createdAt: T,
          updatedAt: T,
          conversations: 2,
          lastConversationId: conversationId,
          openCallbacks: 1,
        },
      ],
      counts: { new: 1 },
    },
  },
  {
    method: 'POST',
    path: '/leads',
    scope: 'leads:write',
    tag: 'Leads',
    summary: 'Create a lead',
    description: 'Adds a contact from elsewhere (your CRM, an import). Needs a name, an email or a phone. One lead per email per site: a second answers 409 with the first one\'s id. Sends `lead.captured` with `source: "api"`.',
    fields: [
      { name: 'name', description: 'Up to 200 characters.' },
      { name: 'email', description: 'One lead per email per site.' },
      { name: 'phone', description: 'Up to 40 characters.' },
      { name: 'company', description: 'Up to 200 characters.' },
      { name: 'address', description: 'Up to 500 characters.' },
      { name: 'attributes', description: 'Custom attributes: an object of strings (up to 50).' },
      { name: 'fields', description: 'Any other details: up to 20 string values.' },
      { name: 'status', description: '`new` (default), `contacted`, `qualified`, `won` or `lost`.' },
      { name: 'notes', description: 'Up to 5000 characters.' },
    ],
    body: { name: 'Grace Hopper', email: 'grace@example.com', phone: '0400 333 444', company: 'US Navy', attributes: { plan: 'pro' }, status: 'new', notes: 'Met at the expo.' },
    status: 201,
    response: { ...leadRow, id: 'lead_7a1c…', name: 'Grace Hopper', email: 'grace@example.com', phone: '0400 333 444', company: 'US Navy', fields: null, source: 'api', conversation_id: null, notes: 'Met at the expo.' },
    nullable: ['conversation_id', 'fields', 'address'],
    errors: [{ status: 409, code: 'conflict', when: 'A lead with this email exists (its id is in the message).' }],
  },
  {
    method: 'GET',
    path: '/leads/:id',
    scope: 'leads:read',
    tag: 'Leads',
    summary: 'Get a lead',
    description: 'The contact with their conversations (status, labels and attributes), the team\'s dated notes (`teamNotes`; `notes` is the contact\'s own notes field) and their callback requests: their history.',
    response: {
      ...leadRow,
      conversations: [
        {
          id: conversationId,
          startedAt: T,
          lastAt: T + 120000,
          pageUrl: 'https://acme.example/pricing',
          firstMessage: 'How much is a blocked drain?',
          messageCount: 6,
          summary: null,
          intent: 'Pricing question',
          channel: 'widget',
          status: 'closed',
          assignedTo: null,
          assignedName: null,
          labels: [{ id: labelRow.id, name: labelRow.name, color: labelRow.color }],
          attributes: { orderId: 'A-1042' },
        },
      ],
      teamNotes: [noteRow],
      callbacks: [callback],
    },
  },
  {
    method: 'POST',
    path: '/leads/:id/notes',
    scope: 'leads:write',
    tag: 'Labels and notes',
    summary: 'Add a note to a contact',
    description: 'A private note for the team about this person.',
    fields: [{ name: 'text', description: 'Up to 5000 characters.', required: true }],
    body: { text: 'Prefers email. Owns two properties.' },
    status: 201,
    response: { ...noteRow, conversationId: null, text: 'Prefers email. Owns two properties.' },
    nullable: ['conversationId', 'authorName'],
  },
  {
    method: 'PATCH',
    path: '/leads/:id',
    scope: 'leads:write',
    tag: 'Leads',
    summary: 'Update a lead',
    description: 'Changes the status, details, notes or custom attributes. `attributes` merges: sent keys are set, `null` removes one. Sends `lead.updated`.',
    fields: [
      { name: 'status', description: '`new`, `contacted`, `qualified`, `won` or `lost`.' },
      { name: 'name', description: 'Up to 200 characters.' },
      { name: 'email', description: 'Changes it (still one lead per email per site).' },
      { name: 'phone', description: 'Up to 40 characters; empty or null clears it.' },
      { name: 'company', description: 'Up to 200 characters; empty or null clears it.' },
      { name: 'address', description: 'Up to 500 characters; empty or null clears it.' },
      { name: 'attributes', description: 'An object of strings; `null` removes a key.' },
      { name: 'notes', description: 'Replaces the notes field (up to 5000 characters). For a dated note, use `POST /leads/:id/notes`.' },
    ],
    body: { status: 'contacted', company: 'Analytical Engines', attributes: { plan: 'pro', trial: null } },
    response: { ...leadRow, status: 'contacted' },
  },
  {
    method: 'DELETE',
    path: '/leads/:id',
    scope: 'leads:write',
    tag: 'Leads',
    summary: 'Delete a lead',
    description: 'Deletes the lead. With `?erase=conversations`, also every conversation linked to it, with their messages and callback requests: for a person who asks to be forgotten.',
    query: [{ name: 'erase', description: '`conversations` to delete the linked conversations too.', example: 'conversations' }],
    response: { id: leadId, deleted: true, conversationsDeleted: 2 },
  },
  {
    method: 'GET',
    path: '/leads.csv',
    scope: 'leads:read',
    tag: 'Leads',
    summary: 'Export leads as CSV',
    description: 'Every lead, newest first. Cells that could run as a spreadsheet formula are prefixed with `\'`.',
    query: [siteQuery],
    csv: 'created,name,email,phone,company,address,status,source,notes,attributes,site,conversation\n2025-10-09T08:53:20.000Z,Ada Lovelace,ada@example.com,0400 111 222,Analytical Engines,,new,form,,"{""plan"":""pro""}",acme,1b0f6a52-…',
  },
  // --------------------------------------------------------------------- jobs
  {
    method: 'GET',
    path: '/jobs',
    scope: 'jobs:read',
    tag: 'Jobs',
    summary: 'List jobs',
    description: 'In board order, up to 500, with each stage\'s count and total value. Open jobs by default.',
    query: [
      { name: 'status', description: '`open` (default), `won`, `lost` or `all`.', example: 'open' },
      { name: 'stage', description: 'One stage\'s id.' },
      { name: 'assigned', description: '`me`, `none`, or a team member\'s email.', example: 'none' },
      { name: 'source', description: '`chat`, `quote`, `api`, `manual` or `callback`.', example: 'api' },
      { name: 'contact', description: 'One contact\'s jobs (their lead id).' },
      { name: 'conversation', description: 'The jobs that came from one conversation.' },
      { name: 'q', description: 'Search title, details, fields, the contact, or a number (`1042`).', example: 'drain' },
      siteQuery,
    ],
    response: { items: [jobRow], stages: [{ ...pipelineRow.stages[0], count: 3, valueCents: 135000 }] },
    nullable: ['dueAt', 'closedAt', 'lostReason', 'assignedTo', 'assignedName', 'value', 'valueCents', 'currency', 'details', 'conversationId', 'contact'],
  },
  {
    method: 'POST',
    path: '/jobs',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Create a job',
    description:
      'From your own form, CRM or automation (Zapier, Make). The contact is matched by email, then phone, or created. `fields` are by field name and checked against the site\'s fields (`GET /jobs/pipeline`): an unknown field or a value that is not one of a choice\'s options is refused, a missing required field is not (the team fills it in). Lands in the first stage unless `stageId` says otherwise. Sends `job.created`.',
    fields: [
      { name: 'title', description: 'Up to 160 characters. Left out: made from the fields and the contact.' },
      { name: 'details', description: 'What is needed, up to 10,000 characters.' },
      { name: 'fields', description: 'Values by field name, e.g. `{ "service": "Blocked drains" }`. A select field takes one of its options.' },
      { name: 'contact', description: '`{ name, email, phone }`: matched by email, then phone, or created.' },
      { name: 'contactId', description: 'An existing contact\'s id, instead of `contact`.' },
      { name: 'conversationId', description: 'The conversation it came from.' },
      { name: 'callbackId', description: 'A callback request to turn into a job (its contact, conversation and reason).' },
      { name: 'stageId', description: 'The stage to start in.' },
      { name: 'value', description: 'What it is worth, e.g. `450` (in `currency`).' },
      { name: 'currency', description: 'ISO 4217, e.g. `AUD`.' },
      { name: 'dueAt', description: 'ISO 8601 date, or milliseconds.' },
      { name: 'assignedTo', description: 'A team member\'s email.' },
    ],
    body: { title: 'Blocked kitchen drain', details: 'Kitchen sink drains slowly and gurgles.', fields: { service: 'Blocked drains', address: 'Balmain', urgency: 'This week' }, contact: { name: 'Ada Lovelace', email: 'ada@example.com', phone: '0400 111 222' }, value: 450, currency: 'AUD' },
    status: 201,
    response: jobRow,
    nullable: ['dueAt', 'closedAt', 'lostReason', 'assignedTo', 'assignedName', 'value', 'valueCents', 'currency', 'details', 'conversationId', 'contact'],
    errors: [{ status: 400, code: 'bad_request', when: 'An unknown field, a value not among a select field\'s options, or a bad email.' }],
  },
  {
    method: 'GET',
    path: '/jobs/:id',
    scope: 'jobs:read',
    tag: 'Jobs',
    summary: 'Get a job',
    description: 'The job with its history (every change, with who and when), notes, and the conversation it came from.',
    response: {
      ...jobRow,
      history: [{ id: 'evt_9b1c2d3e4f5a6b7c', at: T, actor: 'api', actorName: 'Website backend', kind: 'created', data: { source: 'api', stage: 'New request' } }],
      notes: [{ id: 'note_mfx2k1a9', author: 'sam@acme.example', authorName: 'Sam', text: 'Called, booking Tuesday.', createdAt: T, updatedAt: T }],
      conversation: { id: conversationId, firstMessage: 'My kitchen drain is blocked', startedAt: T },
    },
    nullable: ['dueAt', 'closedAt', 'lostReason', 'assignedTo', 'assignedName', 'value', 'valueCents', 'currency', 'details', 'conversationId', 'contact', 'conversation'],
  },
  {
    method: 'PATCH',
    path: '/jobs/:id',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Change a job',
    description: 'Title, details, fields (merged: `null` clears one), value, currency, due date, assignee. Each change goes into the history. Sends `job.updated`.',
    fields: [
      { name: 'title', description: 'Up to 160 characters.' },
      { name: 'details', description: 'Replaces the details. To add to them, use `POST /jobs/:id/updates`.' },
      { name: 'fields', description: 'Values by field name; `null` clears one.' },
      { name: 'value', description: 'A number, or null.' },
      { name: 'currency', description: 'ISO 4217.' },
      { name: 'dueAt', description: 'ISO 8601 date, milliseconds, or null.' },
      { name: 'assignedTo', description: 'A team member\'s email, or null.' },
    ],
    body: { fields: { urgency: 'Emergency' }, value: 520 },
    response: { ...jobRow, fields: { ...jobRow.fields, urgency: 'Emergency' }, value: 520, valueCents: 52000 },
    nullable: ['dueAt', 'closedAt', 'lostReason', 'assignedTo', 'assignedName', 'value', 'valueCents', 'currency', 'details', 'conversationId', 'contact'],
  },
  {
    method: 'POST',
    path: '/jobs/:id/move',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Move a job',
    description: 'To another stage (a won stage closes it and makes the contact won; a lost one closes it, with `lostReason`), and/or another place in its column (`before`: the job it now sits above; null: the bottom). Sends `job.stage_changed`, then `job.won` or `job.lost`.',
    fields: [
      { name: 'stageId', description: 'The stage to move it to.' },
      { name: 'before', description: 'The id of the job it now sits above, or null for the bottom.' },
      { name: 'lostReason', description: 'Why, when moving to a lost stage.' },
    ],
    body: { stageId: 'stg_8d7c6b5a4f3e2d1c' },
    response: { ...jobRow, stage: { id: 'stg_8d7c6b5a4f3e2d1c', name: 'Quote sent', kind: 'open' } },
    nullable: ['dueAt', 'closedAt', 'lostReason', 'assignedTo', 'assignedName', 'value', 'valueCents', 'currency', 'details', 'conversationId', 'contact'],
  },
  {
    method: 'POST',
    path: '/jobs/:id/updates',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Add an update',
    description: 'A dated update in the job\'s history ("Parts ordered, back Thursday"). The details stay as they were.',
    fields: [{ name: 'text', description: 'Up to 4000 characters.', required: true }],
    body: { text: 'Parts ordered, back Thursday.' },
    status: 201,
    response: { id: jobRow.id, added: true },
  },
  {
    method: 'POST',
    path: '/jobs/:id/notes',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Add a note to a job',
    description: 'A private note for the team.',
    fields: [{ name: 'text', description: 'Up to 5000 characters.', required: true }],
    body: { text: 'Gate code 4471.' },
    status: 201,
    response: { id: 'note_mfx2k1a9', jobId: jobRow.id, author: 'key:k7m3p9q2r4s8', authorName: 'Website backend', text: 'Gate code 4471.', createdAt: T, updatedAt: T },
    nullable: ['authorName'],
  },
  {
    method: 'DELETE',
    path: '/jobs/:id',
    scope: 'jobs:write',
    tag: 'Jobs',
    summary: 'Delete a job',
    description: 'With its history and notes. The contact stays.',
    response: { id: jobRow.id, deleted: true },
  },
  {
    method: 'GET',
    path: '/jobs/pipeline',
    scope: 'jobs:read',
    tag: 'Jobs',
    summary: 'The pipeline',
    description: 'The stages (in order; `kind` open, won or lost), the fields a job has (and the question asked for each), the quote questions, which template it came from and why, and the templates there are.',
    query: [siteQuery],
    response: { pipeline: pipelineRow, templates: [templateRow] },
    nullable: ['reason', 'editedAt'],
  },
  {
    method: 'PUT',
    path: '/jobs/pipeline',
    scope: 'settings:write',
    tag: 'Jobs',
    summary: 'Change the pipeline',
    description:
      '`stages` and `fields` are the whole lists, in order: an item with an `id` is changed, one without is added, one left out is removed (a removed stage\'s jobs go to `moveTo[stageId]`, else the first stage of the same kind; a removed field is archived, and jobs keep its values). Keep at least one open, one won and one lost stage. `quote` is the quote questions: field names, in order.',
    fields: [
      { name: 'stages', description: '`[{ id?, name, kind: "open"|"won"|"lost", color?, rotDays? }]`.' },
      { name: 'fields', description: '`[{ id?, label, type: "text"|"textarea"|"number"|"date"|"select"|"email"|"tel", required?, options?, question? }]`.' },
      { name: 'quote', description: 'Field names asked by the widget\'s quote questions, in order (up to 10).' },
      { name: 'quoteEnabled', description: 'Offer the quote questions in the widget ("Get a quote").' },
      { name: 'quoteLabel', description: 'The button\'s label.' },
      { name: 'quoteContact', description: 'Also ask for name, email and phone at the end.' },
      { name: 'assistantJobs', description: 'Let the assistant create jobs from the chat.' },
      { name: 'itemSingular', description: 'What a job is called, e.g. "Ticket".' },
      { name: 'itemPlural', description: 'Its plural.' },
      { name: 'moveTo', description: '`{ <removed stage id>: <stage id> }`.' },
    ],
    body: { quote: ['service', 'description', 'address'], quoteLabel: 'Get a free quote' },
    response: { pipeline: { ...pipelineRow, chosenBy: 'owner', quote: { enabled: true, label: 'Get a free quote', askContact: true } }, templates: [templateRow] },
    nullable: ['reason', 'editedAt'],
  },
  {
    method: 'POST',
    path: '/jobs/pipeline/template',
    scope: 'settings:write',
    tag: 'Jobs',
    summary: 'Use another template',
    description: 'Replaces the stages and fields with a template\'s. Jobs keep their place by stage kind and order; fields the new template lacks are archived.',
    fields: [{ name: 'template', description: '`service-quote`, `projects`, `support`, `sales-demo`, `bookings`, `custom-orders` or `basic`.', required: true }],
    body: { template: 'projects' },
    response: { pipeline: { ...pipelineRow, template: 'projects', chosenBy: 'owner' }, templates: [templateRow] },
    nullable: ['reason', 'editedAt'],
  },
  {
    method: 'POST',
    path: '/jobs/setup',
    scope: 'settings:write',
    tag: 'Jobs',
    summary: 'Let the AI set the pipeline up',
    description: 'Reads the website (what the assistant learned, else the home page), chooses a template and customises it (the site\'s services as options, a stage for its process). Not sure: the basic template. With `force` (the default) it replaces the current pipeline. `helppuff deploy` calls it with `force: false`, which sets Jobs up only if it never was: `status` is `kept` (already set up), `waiting` (the website is still being learned; it is set up when learning finishes) or `done`. Uses Workers AI (a few hundred neurons).',
    fields: [{ name: 'force', description: 'Default true: choose again. False: only the first time, never over a pipeline the owner or the AI set up.' }],
    body: { force: true },
    response: { status: 'done', template: 'service-quote', chosenBy: 'ai', reason: 'A plumbing business with free on-site quotes.', applied: true, pipeline: pipelineRow },
    nullable: ['reason', 'editedAt'],
  },
  // ---------------------------------------------------------------- callbacks
  {
    method: 'GET',
    path: '/callbacks',
    scope: 'callbacks:read',
    tag: 'Callbacks',
    summary: 'List callback requests',
    description: 'Open ones oldest first (the queue); others most recent first. Up to 500, with counts by status.',
    query: [{ name: 'status', description: '`open` (default), `done`, `dismissed` or `all`.', example: 'open' }, siteQuery],
    response: { items: [callback], counts: { open: 1, done: 4, dismissed: 0 } },
  },
  {
    method: 'PATCH',
    path: '/callbacks/:id',
    scope: 'callbacks:write',
    tag: 'Callbacks',
    summary: 'Update a callback request',
    description: 'Mark it done or dismissed (or reopen it), or change its note. Sends `callback.updated`.',
    fields: [
      { name: 'status', description: '`open`, `done` or `dismissed`.' },
      { name: 'note', description: 'What happened (up to 2000 characters); empty clears it.' },
    ],
    body: { status: 'done', note: 'Booked for Tuesday 9am.' },
    response: { ...callback, status: 'done', note: 'Booked for Tuesday 9am.', closedAt: T + 3600000, closedBy: 'key:k7m3p9q2r4s8' },
  },
  // ---------------------------------------------------------------- analytics
  {
    method: 'GET',
    path: '/overview',
    scope: 'analytics:read',
    tag: 'Analytics',
    summary: 'Totals over a period',
    description: 'Conversations, messages, leads and conversion over `days`, against the period before, a day-by-day series, top pages, countries, recent questions and leads.',
    query: [
      { name: 'days', description: '1–365, default 30.', example: '30' },
      { name: 'tz', description: 'Minutes to add to UTC for day boundaries (e.g. 600 for Sydney).', example: '600' },
      siteQuery,
    ],
    response: {
      range: { days: 30, since: T - 30 * 86400000 },
      openCallbacks: 1,
      totals: { conversations: 120, messages: 830, leads: 31, conversion: 0.26, avgMessages: 6.9 },
      previous: { conversations: 98, messages: 640, leads: 22, conversion: 0.22, avgMessages: 6.5 },
      series: [{ date: '2025-10-09', conversations: 5, leads: 1 }],
      topPages: [{ url: 'https://acme.example/pricing', count: 40 }],
      countries: [{ country: 'AU', count: 110 }],
      recentQuestions: [{ id: conversationId, text: 'How much is a blocked drain?', at: T }],
      recentLeads: [{ id: leadId, name: 'Ada Lovelace', email: 'ada@example.com', phone: '0400 111 222', status: 'new', at: T, conversationId }],
    },
  },
  {
    method: 'GET',
    path: '/usage',
    scope: 'analytics:read',
    tag: 'Analytics',
    summary: 'AI usage by day',
    description: 'Today\'s use of the daily budget (Workers AI neurons) and messages, and the last days.',
    query: [siteQuery],
    response: { site: 'acme', today: usage, days: [{ day: '2025-10-08', neurons: 3100, messages: 150 }] },
  },
  {
    method: 'GET',
    path: '/version',
    scope: 'analytics:read',
    tag: 'Analytics',
    summary: 'Running version',
    description: 'The release running, the latest one, and the database schema.',
    response: { current: '0.2.0', latest: '0.3.0', upgradeAvailable: true, schema: { applied: 9, expected: 9 }, command: 'npx @knowtific/helppuff@latest upgrade', releaseNotes: 'https://github.com/knowtific/helppuff/releases' },
  },
  {
    method: 'GET',
    path: '/install-check',
    scope: 'settings:read',
    tag: 'Analytics',
    summary: 'Check the widget is on the website',
    description: 'Fetches the website and looks for the embed snippet.',
    query: [{ name: 'url', description: 'A page to check (defaults to the website).', example: 'https://acme.example/' }, siteQuery],
    response: { url: 'https://acme.example/', reachable: true, installed: true, reason: null },
  },
  // ---------------------------------------------------------------- knowledge
  {
    method: 'GET',
    path: '/knowledge/status',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'Knowledge base status',
    description: 'The latest crawl, page counts, chunks and today\'s AI usage.',
    query: [siteQuery],
    response: {
      site: 'acme',
      connector: 'workers-ai',
      browserRendering: false,
      workflow: true,
      schedule: 'weekly',
      run: { id: 'run_1', status: 'done', trigger: 'dashboard', total: 42, done: 42, failed: 0, chunks: 310, error: null, startedAt: T, finishedAt: T + 90000 },
      pages: { indexed: 40, unchanged: 2 },
      chunks: 310,
      lastIndexedAt: T + 90000,
      usage,
    },
  },
  {
    method: 'POST',
    path: '/knowledge/discover',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Find the website pages',
    description: 'Reads robots.txt and the sitemaps, and suggests which pages to learn.',
    body: {},
    response: { site: 'acme', origin: 'https://acme.example', reachable: true, sitemaps: ['https://acme.example/sitemap.xml'], warnings: [], urls: [{ url: 'https://acme.example/pricing', category: 'pricing', suggested: true, status: 'indexed', title: 'Pricing', error: null, selected: true }] },
  },
  {
    method: 'POST',
    path: '/knowledge/crawl',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Learn the website',
    description: 'Crawls the given pages (or the selected ones) in the background. Follow progress with `GET /knowledge/status`.',
    fields: [
      { name: 'urls', description: 'The pages to learn. Without it, the selected pages.' },
      { name: 'include', description: 'Glob patterns of pages to add, e.g. `["/services/**"]`.' },
      { name: 'exclude', description: 'Glob patterns of pages to leave out.' },
    ],
    body: { urls: ['https://acme.example/pricing', 'https://acme.example/services'] },
    status: 202,
    response: { site: 'acme', runId: 'run_2', total: 2 },
  },
  {
    method: 'POST',
    path: '/knowledge/crawl/retry',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Try failed pages again',
    description:
      'Crawls the pages that failed (or the given ones among them) again, in the background, without changing which pages are selected. Pages that failed for a passing reason are also retried by themselves after a crawl. `409` while a crawl is running.',
    fields: [{ name: 'urls', description: 'Only these failed pages. Without it, every failed page.' }],
    body: { urls: ['https://acme.example/industries'] },
    status: 202,
    response: { site: 'acme', runId: 'run_3', total: 1 },
  },
  {
    method: 'POST',
    path: '/knowledge/runs/:id/cancel',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Cancel a crawl',
    response: { cancelled: true },
  },
  {
    method: 'GET',
    path: '/knowledge/pages',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'List learned pages',
    query: [{ name: 'status', description: '`discovered`, `indexed`, `unchanged`, `failed`…', example: 'indexed' }, siteQuery],
    response: { site: 'acme', pages: [{ id: 'pg_1', url: 'https://acme.example/pricing', finalUrl: 'https://acme.example/pricing', title: 'Pricing', category: 'pricing', status: 'indexed', httpStatus: 200, error: null, selected: 1, source: 'crawl', crawledAt: T, chunks: 6 }] },
  },
  {
    method: 'GET',
    path: '/knowledge/pages/:id/chunks',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'Chunks of a page',
    description: 'The passages the assistant searches, as stored.',
    query: [siteQuery],
    response: { chunks: [{ id: 'ch_1', headingPath: 'Pricing › Drains', ordinal: 0, content: 'Blocked drains: $180–$250 including the first hour.', tokens: 14 }] },
  },
  {
    method: 'POST',
    path: '/knowledge/search',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'Search the knowledge base',
    description: 'What the assistant would find for a question (hybrid search, then the reranker). A few neurons.',
    fields: [
      { name: 'query', description: 'The question (up to 1000 characters).', required: true },
      { name: 'k', description: 'How many passages to return.' },
      { name: 'rerank', description: '`false` to skip the reranker.' },
    ],
    body: { query: 'blocked drain price', k: 3 },
    response: {
      site: 'acme',
      query: 'blocked drain price',
      neurons: 2.1,
      chunks: [{ id: 'ch_1', pageId: 'pg_1', url: 'https://acme.example/pricing', title: 'Pricing', headingPath: 'Pricing › Drains', category: 'pricing', content: 'Blocked drains: $180–$250…', ordinal: 0, score: 0.91 }],
      trace: { vector: 8, keyword: 5, fused: 10, reranked: true, threshold: 0.2, errors: [], ms: { embed: 40, vector: 30, keyword: 6, rerank: 120 } },
    },
  },
  {
    method: 'POST',
    path: '/knowledge/suggest-questions',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'Suggest starter questions',
    description: 'Four questions a customer might ask, written from what the site taught the assistant.',
    body: {},
    response: { questions: ['How much is a blocked drain?', 'Do you do emergency callouts?', 'Which suburbs do you cover?', 'Can I book online?'], source: 'model' },
  },
  {
    method: 'POST',
    path: '/assistant/test',
    scope: 'settings:write',
    tag: 'Settings',
    summary: 'Test the model or the knowledge base',
    description:
      'One question through the deployed assistant\'s own model (`part: "model"`) or knowledge base (`part: "knowledge"`), as configured: keys, gateway and custom modules included. Nothing is recorded. A failure answers `ok: false` with what to fix (a missing secret, a refused key). What `helppuff model test` and `helppuff rag test` call. The model and knowledge base are changed only with the CLI, then a deploy.',
    fields: [
      { name: 'part', description: '`model` (default) or `knowledge`.' },
      { name: 'question', description: 'What to ask or search for.' },
    ],
    body: { part: 'model', question: 'Do you do emergency callouts?' },
    response: { provider: 'openai-compatible', knowledge: 'helppuff', part: 'model', ok: true, model: 'deepseek-ai/DeepSeek-V3.1', reply: 'Yes, we answer emergency callouts 24/7.', usage: { input: 42, output: 11 }, ms: 812 },
    nullable: ['usage'],
  },
  {
    method: 'POST',
    path: '/home/suggest',
    scope: 'settings:write',
    tag: 'Settings',
    summary: 'Suggest the home screen',
    description: 'From what the site taught the assistant: four questions visitors ask, up to five useful pages as links (chosen and worded by the AI, only URLs the site has), and call and email buttons from the business details. Nothing is saved: send what you keep to `PUT /settings` as `home`.',
    body: {},
    response: {
      questions: ['How much is a blocked drain?', 'Do you do emergency callouts?'],
      links: homeLinks,
      contact: [{ id: 'call', label: 'Call us', description: '02 9000 0000', icon: 'phone', action: { id: 'call', kind: 'tel', label: 'Call us', phone: '02 9000 0000' } }],
      source: 'model',
    },
    nullable: ['links'],
  },
  {
    method: 'GET',
    path: '/knowledge/manual',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'List hand-written knowledge',
    query: [siteQuery],
    response: { entries: [{ id: 'holiday-hours', title: 'Holiday hours', content: 'Closed 25–26 December.', updatedAt: T }] },
  },
  {
    method: 'POST',
    path: '/knowledge/manual',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Add or replace hand-written knowledge',
    description: 'Searchable at once. The same `id` replaces an entry.',
    fields: [
      { name: 'title', description: 'Up to 200 characters.', required: true },
      { name: 'content', description: 'Markdown or plain text, up to 100,000 characters.', required: true },
      { name: 'id', description: 'Lowercase letters, digits and `-`. The same id replaces an entry.' },
    ],
    body: { id: 'holiday-hours', title: 'Holiday hours', content: 'We are closed on 25 and 26 December.' },
    response: { id: 'holiday-hours', chunks: 1 },
  },
  {
    method: 'DELETE',
    path: '/knowledge/manual/:id',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Remove hand-written knowledge',
    query: [siteQuery],
    response: { deleted: true },
  },
  {
    method: 'GET',
    path: '/knowledge/files',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'List uploaded files',
    query: [siteQuery],
    response: { files: [{ id: '0b8f…', name: 'price-list.pdf', kind: 'pdf', size: 182044, status: 'indexed', error: null, chunks: 12, truncated: 0, createdAt: T, updatedAt: T }] },
  },
  {
    method: 'POST',
    path: '/knowledge/files',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Upload a file',
    description: 'The raw bytes as the body, the file name as `?name=`. PDF, Word (.docx), Markdown or text, up to 10 MB. Read and learned in the background.',
    query: [{ name: 'name', description: 'The file name, with its extension.', required: true, example: 'price-list.pdf' }, siteQuery],
    raw: { contentType: 'application/octet-stream', description: 'The file\'s bytes.' },
    status: 202,
    response: { id: '0b8f…', name: 'price-list.pdf', kind: 'pdf', size: 182044, status: 'queued' },
  },
  {
    method: 'DELETE',
    path: '/knowledge/files/:id',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Remove an uploaded file',
    description: 'And everything learned from it.',
    query: [siteQuery],
    response: { deleted: true, chunks: 12 },
  },
  {
    method: 'GET',
    path: '/knowledge/facts',
    scope: 'knowledge:read',
    tag: 'Knowledge',
    summary: 'Business details',
    description: 'Phone, email, address, hours, service areas: read from the site (`crawl`) or set by you (`owner`).',
    query: [siteQuery],
    response: { facts: [{ key: 'phone', value: '1300 000 000', source: 'owner', sourceUrl: 'owner' }] },
  },
  {
    method: 'PUT',
    path: '/knowledge/facts',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Set business details',
    description: 'Yours are never overwritten by a crawl. An empty value removes one. Re-indexed at once.',
    fields: [{ name: 'facts', description: 'Keys `name`, `phone`, `email`, `address`, `hours`, `serviceAreas` and others; an empty value removes one.', required: true }],
    body: { facts: { phone: '1300 000 000', hours: 'Mon–Fri 8am–5pm' } },
    response: { facts: [{ key: 'phone', value: '1300 000 000' }, { key: 'hours', value: 'Mon–Fri 8am–5pm' }] },
  },
  {
    method: 'POST',
    path: '/knowledge/facts/detect',
    scope: 'knowledge:write',
    tag: 'Knowledge',
    summary: 'Read business details from the site',
    body: {},
    response: { found: 4, facts: [{ key: 'phone', value: '1300 000 000', source: 'site' }] },
  },
  // ------------------------------------------------------------------- prompt
  {
    method: 'GET',
    path: '/prompt',
    scope: 'prompt:read',
    tag: 'Prompt',
    summary: 'The prompt and its versions',
    description: 'The business-specific instructions, everything HelpPuff adds around them (`builtIn`), lines that repeat a setting (`overlaps`), and the version history.',
    query: [siteQuery],
    response: { site: 'acme', connector: 'workers-ai', builtIn: 'You are the website assistant for Acme…', overlaps: [], editable: true, reason: null, text: 'We service the Inner West only.', hash: '9f2c…', version: 3, meta: { version: 3, hash: '9f2c…', at: T, by: 'owner@acme.example', source: 'dashboard' }, limit: 16000, versions: [{ version: 3, hash: '9f2c…', source: 'dashboard', author: 'owner@acme.example', note: null, restoredFrom: null, createdAt: T, chars: 31 }] },
  },
  {
    method: 'GET',
    path: '/prompt/versions/:version',
    scope: 'prompt:read',
    tag: 'Prompt',
    summary: 'One prompt version',
    query: [siteQuery],
    response: { version: 2, hash: '1d4e…', source: 'cli', author: 'cli', note: null, restoredFrom: null, createdAt: T, chars: 38, text: 'We service the Inner West and the CBD.' },
  },
  {
    method: 'POST',
    path: '/prompt',
    scope: 'prompt:write',
    tag: 'Prompt',
    summary: 'Publish a prompt version',
    description: 'Live within a minute. `baseVersion` is the version you edited: if someone published since, the answer is 409 with theirs.',
    fields: [
      { name: 'text', description: 'The whole prompt (up to 16,000 characters).', required: true },
      { name: 'baseVersion', description: 'The version you edited (from `GET /prompt`).', required: true },
      { name: 'note', description: 'What changed, for the history.' },
    ],
    body: { text: 'We service the Inner West only. Never quote for gas work.', baseVersion: 3, note: 'No gas quotes' },
    response: { status: 'published', version: 4, hash: 'a1b2…' },
    errors: [{ status: 409, code: 'bad_request', when: 'Someone published a newer version (it is in the body).' }],
  },
  {
    method: 'POST',
    path: '/prompt/restore',
    scope: 'prompt:write',
    tag: 'Prompt',
    summary: 'Restore a prompt version',
    description: 'Publishes an old version\'s text as a new version.',
    body: { version: 2, baseVersion: 4 },
    response: { status: 'published', version: 5, hash: 'c3d4…' },
  },
  {
    method: 'GET',
    path: '/agent/export',
    scope: 'prompt:read',
    tag: 'Prompt',
    summary: 'Export the agent file',
    description:
      'The assistant\'s setup as one file, to keep in a project, share or import elsewhere: the prompt, the tools, and the behaviour and lead form settings. A tool\'s secret header is a placeholder (`${ORDER_STATUS_AUTHORIZATION}`), listed in `needs`; its value never leaves the Worker.',
    query: [siteQuery],
    response: agentFile,
  },
  {
    method: 'POST',
    path: '/agent/import',
    scope: 'prompt:write',
    tag: 'Prompt',
    summary: 'Import an agent file',
    description:
      'Applies an agent file (from `GET /agent/export`, a template, or written by hand): its settings, its tools (matched by name: created or replaced) and its prompt, as a new version. Everything is checked before anything changes. With `dryRun`, nothing changes: the answer says what would, and which secrets are still needed. Importing a file with `settings` (not a dry run) needs the `settings:write` scope too.',
    fields: [
      { name: 'agent', description: 'The agent file: `{ "helppuff": "agent", "version": 1, name, prompt, settings, tools, needs }`.', required: true },
      { name: 'secrets', description: 'A value for each `${NAME}` in the tools\' headers, as `{ "NAME": "value" }`. Stored encrypted, as a tool saved by hand. A tool that already has the header keeps its value when one is left out.' },
      { name: 'dryRun', description: '`true`: change nothing, answer what would change.' },
    ],
    body: { agent: agentFile, secrets: { ORDER_STATUS_AUTHORIZATION: 'Bearer sk_live_…' }, dryRun: true },
    response: {
      site: 'acme',
      dryRun: true,
      ready: true,
      name: 'Acme Plumbing assistant',
      settings: ['behaviour', 'leads'],
      tools: [
        { name: 'order_number', action: 'create' },
        { name: 'order_status', action: 'create' },
      ],
      prompt: { action: 'replace', version: 4 },
      missingSecrets: [],
    },
    errors: [{ status: 400, code: 'bad_request', when: 'The file is not valid (`agent_invalid`), or a secret is missing (`agent_secrets_missing`).' }],
  },
  // -------------------------------------------------------------------- tools
  {
    method: 'GET',
    path: '/tools',
    scope: 'prompt:read',
    tag: 'Tools',
    summary: 'List tools',
    description: 'Every tool the site has. Secret header values are never returned: `set` says whether one is stored. `keys` are what the tool returns (from its last test), for `{{name.key}}` in the prompt. `prechat` is the pre-chat form\'s fields (`{{prechat.<name>}}`); `assistant` whether the site\'s backend is HelpPuff\'s assistant, which uses tools in the chat.',
    query: [siteQuery],
    response: { tools: [tool], assistant: true, prechat: [{ name: 'email', label: 'Email' }], limits: { tools: 30, timeoutMs: { default: 5000, min: 1000, max: 10000 } } },
    nullable: ['tools.lastStatus', 'tools.lastAt'],
  },
  {
    method: 'POST',
    path: '/tools',
    scope: 'prompt:write',
    tag: 'Tools',
    summary: 'Add a tool',
    description:
      'An `http` tool calls your API: `{{args.x}}` in its URL, headers or body is filled in by the assistant, `{{prechat.email}}` from the pre-chat form, `{{data.other_tool.key}}` from what another tool returned. An `extract` tool calls nothing: the assistant saves its `fields` (as conversation attributes too). Name it in the prompt as `{{name}}` to let the assistant use it; `before` runs it when the chat starts, `after` when the conversation ends. Up to 30 per site.',
    fields: [
      { name: 'name', description: 'Lowercase letters, digits and `_`, starting with a letter: how the prompt and the data refer to it.', required: true },
      { name: 'kind', description: '`http` (the default) or `extract`.' },
      { name: 'description', description: 'What it does and when to use it: the assistant reads it.', required: true },
      { name: 'method', description: '`GET`, `POST`, `PUT`, `PATCH` or `DELETE`.' },
      { name: 'url', description: 'An https URL; only its path and query may use `{{…}}`.' },
      { name: 'headers', description: 'A list of `{ name, value, secret }`; secret values are stored encrypted and never returned.' },
      { name: 'body', description: 'The request body; in JSON, `"{{data}}"` as a whole value sends the object itself.' },
      { name: 'parameters', description: 'Descriptions of the `{{args.*}}` the request uses: `{ name, description, required }`.' },
      { name: 'fields', description: 'An extract tool\'s fields: `{ name, description, required }`.' },
      { name: 'pick', description: 'Response paths to keep (`delivery.date`); empty keeps it all (cut to about 4 KB).' },
      { name: 'timeoutMs', description: '1000 to 10000 (default 5000).' },
      { name: 'before', description: 'Run it when the chat starts, with the pre-chat form\'s answers.' },
      { name: 'after', description: 'Run it when the conversation ends, with the transcript, the summary, the lead and all the data.' },
      { name: 'when', description: 'An after-chat tool runs only when this holds: `{ "path": "labels.leadQuality", "in": ["hot"] }` (a path in the conversation.completed data and the values it may have), or `{ "path": "lead.email" }` (has a value). `null` removes it.' },
    ],
    body: {
      name: 'order_status',
      description: 'Look up an order by its number: status, items and delivery date.',
      method: 'GET',
      url: 'https://api.acme.example/orders/{{args.order_number}}',
      headers: [{ name: 'Authorization', value: 'Bearer sk_live_4f3e2d1c', secret: true }],
      parameters: [{ name: 'order_number', description: 'The order number, like A-1042.', required: true }],
      pick: ['status', 'delivery.date'],
    },
    status: 201,
    response: tool,
    nullable: ['lastStatus', 'lastAt'],
  },
  {
    method: 'PATCH',
    path: '/tools/:id',
    scope: 'prompt:write',
    tag: 'Tools',
    summary: 'Change a tool',
    description: 'Any of the fields `POST /tools` takes. A secret header sent with an empty value keeps the stored one.',
    body: { before: true },
    response: { ...tool, before: true },
    nullable: ['lastStatus', 'lastAt'],
  },
  {
    method: 'DELETE',
    path: '/tools/:id',
    scope: 'prompt:write',
    tag: 'Tools',
    summary: 'Remove a tool',
    description: 'Conversations keep what it returned. Take `{{name}}` out of the prompt too.',
    query: [siteQuery],
    response: { deleted: true },
  },
  {
    method: 'POST',
    path: '/tools/test',
    scope: 'prompt:write',
    tag: 'Tools',
    summary: 'Test a tool',
    description:
      'Calls it now with sample values and shows what came back: a saved tool (`id`), a draft (`tool`), or both (unsaved changes; empty secret headers keep the stored ones). `response` is the whole answer, `value` what a chat keeps (after `pick`), `keys` its key paths; testing a saved tool remembers them.',
    fields: [
      { name: 'id', description: 'A saved tool.' },
      { name: 'tool', description: 'A draft, as `POST /tools` takes it.' },
      { name: 'sample', description: 'Values for the templates: `{ args, prechat, data, page, conversation, transcript, summary, lead, attributes }`.' },
    ],
    body: { id: 'tool_8d7c6b5a', sample: { args: { order_number: 'A-1042' } } },
    response: { ok: true, status: 200, ms: 182, error: null, response: { status: 'shipped', delivery: { date: '2026-10-12', carrier: 'AusPost' } }, value: { status: 'shipped', delivery: { date: '2026-10-12' } }, keys: ['status', 'delivery', 'delivery.date', 'delivery.carrier'] },
    nullable: ['status', 'error'],
  },
  // ----------------------------------------------------------------- settings
  {
    method: 'GET',
    path: '/settings',
    scope: 'settings:read',
    tag: 'Settings',
    summary: 'The settings',
    description: 'The assistant, widget, home screen, lead form, crawl and security settings as one object, with a hash of it. Also: `ai`, who writes the answers and what they come from (changed only with the CLI, `helppuff model` and `helppuff rag`, then a deploy); `suggestedHome`, what the widget shows on its home screen until it is set up (questions and links suggested from the website; null once the home screen was saved), and the `forms` and `flows` a shortcut can open.',
    query: [siteQuery],
    response: {
      site: 'acme',
      connector: 'workers-ai',
      settings,
      hash: '5c1e…',
      meta: null,
      captcha: false,
      suggestedHome: { questions: ['How much is a blocked drain?'], links: homeLinks, at: T },
      ai: { provider: 'workers-ai', model: '@cf/zai-org/glm-4.7-flash', knowledge: 'helppuff' },
      forms: [{ id: 'booking', title: 'Book a visit' }],
      flows: [{ id: 'quote', title: 'Which service do you need?' }],
    },
    nullable: ['suggestedHome', 'meta', 'ai'],
  },
  {
    method: 'PUT',
    path: '/settings',
    scope: 'settings:write',
    tag: 'Settings',
    summary: 'Change settings',
    description: 'A partial update: send only the sections to change (nested objects merge one level deep). Live within a minute. Run `helppuff config pull` afterwards if you keep helppuff.json in git.',
    fields: [
      {
        name: 'settings',
        description:
          'Any sections of the object `GET /settings` returns: `botName`, `welcomeMessage`, `leads`, `assistant`, `behaviour`, `crawl`, `security`, `home` … `home.shortcuts` is the whole list of home-screen buttons (up to 8; each `action.kind` is `reply`, `url`, `tel`, `email`, `form` or `flow`); `home.links` the list of pages, or null for none. Saving `home` retires the suggestions from the website.',
        required: true,
      },
    ],
    body: { settings: { welcomeMessage: 'Hi! Ask me anything about our plumbing services.', security: { limits: { messagesPerSitePerDay: 800 } } } },
    response: { site: 'acme', connector: 'workers-ai', settings: { ...settings, welcomeMessage: 'Hi! Ask me anything about our plumbing services.' }, hash: '7d2a…', meta: { at: T, by: 'key:k7m3p9q2r4s8', hash: '7d2a…' }, captcha: false },
  },
  // ----------------------------------------------------------------- webhooks
  {
    method: 'GET',
    path: '/webhooks',
    scope: 'webhooks:read',
    tag: 'Webhooks',
    summary: 'List webhook endpoints',
    description: 'With every event type there is to subscribe to.',
    query: [siteQuery],
    response: { webhooks: [webhook], events: [{ type: 'lead.captured', description: 'Contact details arrived…' }] },
  },
  {
    method: 'POST',
    path: '/webhooks',
    scope: 'webhooks:write',
    tag: 'Webhooks',
    summary: 'Add a webhook endpoint',
    description: 'An https URL and the events it wants (`["*"]` or absent: all). Deliveries are signed with the returned `secret`. Up to 10 per site.',
    fields: [
      { name: 'url', description: 'An https URL.', required: true },
      { name: 'events', description: 'Event types (`GET /webhooks` lists them), or `["*"]` for all (the default).' },
      { name: 'description', description: 'Up to 200 characters.' },
    ],
    body: { url: 'https://hooks.example.com/helppuff', events: ['lead.captured', 'callback.requested'], description: 'CRM sync' },
    status: 201,
    response: webhook,
  },
  {
    method: 'PATCH',
    path: '/webhooks/:id',
    scope: 'webhooks:write',
    tag: 'Webhooks',
    summary: 'Change a webhook endpoint',
    description: 'Any of `url`, `events`, `enabled`, `description`; `rotateSecret: true` makes a new signing secret.',
    body: { enabled: false },
    response: { ...webhook, enabled: false },
  },
  {
    method: 'DELETE',
    path: '/webhooks/:id',
    scope: 'webhooks:write',
    tag: 'Webhooks',
    summary: 'Remove a webhook endpoint',
    query: [siteQuery],
    response: { deleted: true },
  },
  {
    method: 'POST',
    path: '/webhooks/:id/test',
    scope: 'webhooks:write',
    tag: 'Webhooks',
    summary: 'Send a test event',
    description: 'Delivers a signed `test.ping` now and says what came back.',
    body: {},
    response: { ok: true, status: 200, error: null, attempts: 1, durationMs: 182, retryable: false, eventId: 'evt_4f3e2d1c' },
  },
  {
    method: 'GET',
    path: '/webhooks/:id/deliveries',
    scope: 'webhooks:read',
    tag: 'Webhooks',
    summary: 'Recent deliveries',
    description: 'The last 50 attempts for an endpoint.',
    query: [siteQuery],
    response: { deliveries: [{ id: 'd_1', eventId: 'evt_4f3e2d1c', event: 'lead.captured', ok: true, status: 200, error: null, attempts: 1, durationMs: 182, at: T }] },
  },
  // --------------------------------------------------------------------- team
  {
    method: 'GET',
    path: '/admins',
    scope: 'team:read',
    tag: 'Team',
    summary: 'List dashboard accounts',
    description: 'Each account\'s `role`: `admin` (everything) or `member` (conversations, jobs, contacts, callbacks and live chat only).',
    response: { me: 'key:k7m3p9q2r4s8', owner: 'owner@acme.example', admins: [{ email: 'sam@acme.example', name: 'Sam', role: 'member', createdAt: T, lastLoginAt: T }] },
  },
  {
    method: 'POST',
    path: '/admins',
    scope: 'team:write',
    tag: 'Team',
    summary: 'Add a dashboard account',
    description: 'With a `password` (10+ characters) they can sign in at once; without one, the answer has a one-time sign-in link (7 days) to send them. `team:write` can give dashboard access: treat it like full access.',
    fields: [
      { name: 'email', description: 'Their email address.', required: true },
      { name: 'name', description: 'Up to 100 characters.' },
      { name: 'password', description: '10+ characters. Without it, the answer has a sign-in link.' },
      { name: 'role', description: '`admin` (default: everything) or `member` (conversations, jobs, contacts, callbacks and live chat; no settings).' },
    ],
    body: { email: 'sam@acme.example', name: 'Sam', role: 'member' },
    status: 201,
    response: { email: 'sam@acme.example', name: 'Sam', role: 'member', createdAt: T, signInLink: 'https://helppuff.example.workers.dev/admin/#/signin/9xQ…', signInLinkExpiresAt: T + 7 * 86400000 },
    errors: [{ status: 409, code: 'conflict', when: 'The email can already sign in.' }],
  },
  {
    method: 'PATCH',
    path: '/admins/:email',
    scope: 'team:write',
    tag: 'Team',
    summary: 'Change a role or name',
    description: '`role`: `admin` or `member`. The owner always has full access.',
    fields: [
      { name: 'role', description: '`admin` or `member`.' },
      { name: 'name', description: 'Up to 100 characters: the first name visitors see in live chat.' },
    ],
    body: { role: 'admin' },
    response: { email: 'sam@acme.example', name: 'Sam', role: 'admin', createdAt: T, lastLoginAt: T },
    nullable: ['name', 'lastLoginAt'],
  },
  {
    method: 'DELETE',
    path: '/admins/:email',
    scope: 'team:write',
    tag: 'Team',
    summary: 'Remove a dashboard account',
    description: 'They are signed out at their next request. The owner (set in the Worker\'s config) cannot be removed here.',
    response: { email: 'sam@acme.example', deleted: true },
  },
  {
    method: 'POST',
    path: '/admins/:email/sign-in-link',
    scope: 'team:write',
    tag: 'Team',
    summary: 'Make a one-time sign-in link',
    description: 'Valid 15 minutes, once. The way back in after a lost password.',
    status: 201,
    response: { email: 'sam@acme.example', url: 'https://helppuff.example.workers.dev/admin/#/signin/7bR…', expiresAt: T + 900000 },
  },
  // --------------------------------------------------------------------- keys
  {
    method: 'GET',
    path: '/keys',
    scope: 'keys:read',
    tag: 'API keys',
    summary: 'List API keys',
    description: 'Never their secrets. With the scopes and presets there are.',
    query: [siteQuery],
    response: { keys: [keyView], scopes: [{ scope: 'chat', description: 'Talk to the assistant as a visitor…' }], presets: [{ id: 'chat', label: 'Chat only', scopes: ['chat'] }] },
  },
  {
    method: 'POST',
    path: '/keys',
    scope: 'keys:write',
    tag: 'API keys',
    summary: 'Create an API key',
    description: 'The full key is in this answer only: store it in your secrets manager. A key cannot create a key with scopes it does not have.',
    fields: [
      { name: 'name', description: 'What the key is for.', required: true },
      { name: 'preset', description: '`chat`, `crm`, `read` or `full`. Or, instead:' },
      { name: 'scopes', description: 'A list of scopes (see the API page).' },
      { name: 'expiresInDays', description: '1–3650; absent or null: never.' },
      { name: 'allowIps', description: 'IP addresses or CIDR ranges it may be used from.' },
      { name: 'ratePerMinute', description: 'Requests a minute (default 120).' },
    ],
    body: { name: 'Website backend', preset: 'chat', expiresInDays: 365 },
    status: 201,
    response: { key: 'hp_live_k7m3p9q2r4s8_Zx1…', ...keyView, scopes: ['chat'], expiresAt: T + 365 * 86400000 },
    errors: [{ status: 403, code: 'forbidden', when: 'The calling key would hand out scopes it does not have.' }],
  },
  {
    method: 'DELETE',
    path: '/keys/:id',
    scope: 'keys:write',
    tag: 'API keys',
    summary: 'Revoke an API key',
    description: 'Refused everywhere within 30 seconds. `:id` is the key\'s id or prefix.',
    query: [siteQuery],
    response: { ...keyView, revokedAt: T + 60000, revoked: true },
  },
  // -------------------------------------------------------------------- audit
  {
    method: 'GET',
    path: '/audit',
    scope: 'audit:read',
    tag: 'Audit',
    summary: 'Audit log',
    description: 'Every change made through the API or the dashboard, newest first, kept 90 days. Pass `next` as `before` for the next page.',
    query: [{ name: 'before', description: 'Cursor: the `next` of the previous page.' }, { name: 'limit', description: '1–200, default 50.', example: '50' }],
    response: { items: [{ id: 'au_1', at: T, actor: 'key:k7m3p9q2r4s8', action: 'PATCH /leads/:id', target: leadId, site: 'acme', status: 200 }], next: null },
  },
  // ---------------------------------------------------- the dashboard's own
  ...(['GET /prefs', 'PUT /prefs', 'POST /login', 'POST /logout', 'GET /login/options', 'POST /links', 'GET /setup', 'POST /setup', 'POST /login-link', 'GET /setup/state', 'POST /diagnostics/models', 'GET /identity', 'POST /identity/rotate'] as const).map((route) => {
    const [method, path] = route.split(' ') as [Method, string];
    return { method, path, scope: null, tag: 'Dashboard', summary: 'The dashboard\'s own (not part of the public API)' } satisfies Endpoint;
  }),
];

/** `/leads/:id` → a regex for the path relative to the base. */
function pattern(path: string): RegExp {
  return new RegExp(`^${path.replace(/[.]/g, '\\.').replace(/:[A-Za-z]+/g, '[^/]+')}$`);
}
const compiled = ENDPOINTS.map((endpoint) => ({ endpoint, re: pattern(endpoint.path) }));

/** The registry entry for a request, relative to the base (`/leads/abc`). Literal paths win over parameters. */
export function findEndpoint(method: string, path: string): Endpoint | null {
  const matches = compiled.filter((e) => e.endpoint.method === method && e.re.test(path));
  if (!matches.length) return null;
  return (matches.find((m) => !m.endpoint.path.includes(':')) ?? matches[0]!).endpoint;
}

/** The public endpoints (what the docs describe). */
export const PUBLIC_ENDPOINTS = ENDPOINTS.filter((e) => e.scope !== null);
